version: "3.1"

services:
  broker:
    image: "rabbitmq:alpine"
    restart: always

  result:
    image: "redis:alpine"
    restart: always

  frontend:
    build:
      dockerfile: frontend/Dockerfile.prod
      context: .
    ports:
      - "80:80"
    env_file: frontend/.env
    depends_on:
      - backend
    restart: always

  backend:
    build:
      dockerfile: backend/Dockerfile.prod
      context: .
    ports:
      - "8000:8000"
    env_file: backend/.env
    depends_on:
      - broker
      - result
    restart: always

  celery:
    build:
      dockerfile: backend/Dockerfile.prod
      context: .
    command: celery -A siscme worker -B -l DEBUG -s /tmp/celerybeat-schedule
    env_file: backend/.env
    depends_on:
      - broker
      - result
    restart: always
