[tool.isort]
profile = "black"
known_third_party = ["drf_spectacular"]
line_length = 79

[tool.black]
line-length = 79
target-version = ['py310']
quiet = true
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.venv
  | _build
  | build
  | dist
  | [a-z_]+/migrations
)/
'''
