import { StyleSheet } from "@react-pdf/renderer"

const geral = {
	page: {
		display: `flex`,
		padding: `30px 20px 20px 30px`,
		flexDirection: `column`,
		backgroundColor: `#ffffff`,
	},
	pageEtiqueta: {
		display: `flex`,
		padding: `10px`,
		flexDirection: `column`,
		backgroundColor: `#ffffff`,
	},
	pageQrcode: {
		display: `flex`,
		padding: `10px`,
		flexDirection: `column`,
		alignItems: `center`,
		backgroundColor: `#ffffff`,
	},
	section: {
		margin: 10,
		padding: 10,
		flexGrow: 1,
	},
	logo: {
		height: `64`,
	},
	logo48: {
		height: `48`,
	},
	logoQRCode: {
		height: `164`,
		width: `164`,
	},

	container: {
		flexDirection: `row`,
		alignItems: `stretch`,
		justifyContent: `space-between`,
	},
	containerTable: {
		flexDirection: `column`,
	},
	row: {
		display: `flex`,
		flexDirection: `row`,
	},
	rowWithGap: {
		display: `flex`,
		flexDirection: `row`,
		gap: `20px`,
	},
	rowMargin: {
		display: `flex`,
		flexDirection: `row`,
		marginTop: `20px`,
	},
	column: {
		flexDirection: `column`,
	},
	pageNumber: {
		position: `absolute`,
		fontSize: 10,
		bottom: 20,
		left: 30,
		right: 20,
		textAlign: `center`,
		color: `grey`,
	},
	pageNumber1: {
		position: `absolute`,
		fontSize: 10,
		bottom: 5,
		left: 30,
		right: 20,
		textAlign: `center`,
		color: `grey`,
	},
	rodapeText: {
		color: `black`,
		fontSize: 10,
		fontWeight: `normal`,
		width: `auto`,
	},
}
const header = {
	headerBorderAll: {
		padding: `4px 8px 0px 4px`,
		flexDirection: `column`,
		borderWidth: 2,
		borderColor: `#0e0606`,
		borderStyle: `solid`,
		borderRadius: `0%`,
		alignItems: `flex-start`,
		justifyContent: `space-between`,
	},
	headerWithoutBorder: {
		padding: `14px 8px 0px 4px`,
		flexDirection: `column`,
		alignItems: `flex-start`,
		justifyContent: `space-between`,
	},
	rowHeader: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `18px`,
		justifyContent: `space-between`,
		//border: '1px solid orange',
		width: `100%`,
	},
	rowHeader3: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `15px`,
		justifyContent: `space-between`,
		//border: '1px solid orange',
		width: `100%`,
	},
	rowHeader4: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `15px`,
		// justifyContent: `space-between`,
		//border: '1px solid orange',
		width: `100%`,
	},
	columnHeader: {
		display: `flex`,
		flexDirection: `column`,
		alignItems: `baseline`,
		height: `18px`,
		justifyContent: `space-between`,
		//border: '1px solid orange',
		width: `100%`,
	},
	headerTitle: {
		color: `black`,
		fontSize: `10px`,
		height: `15px`,
		fontFamily: `Lato Bold`,
		fontWeight: `bold`,
		fontStyle: `normal`,
		marginRight: `4px`,
	},
	headerTitle1: {
		color: `black`,
		fontSize: `12px`,
		height: `15px`,
		fontFamily: `Lato Bold`,
		fontWeight: `bold`,
		fontStyle: `normal`,
	},
	headerTitle2: {
		color: `black`,
		fontSize: `8px`,
		height: `15px`,
		fontFamily: `Lato Bold`,
		fontWeight: `bold`,
		fontStyle: `normal`,
	},
	headerTitleEtiqueta: {
		color: `black`,
		fontSize: `8px`,
		height: `15px`,
		fontFamily: `Lato Bold`,
		fontWeight: `bold`,
		fontStyle: `normal`,
	},
	headerTitleEtiqueta1: {
		color: `black`,
		fontSize: `8px`,
		height: `12px`,
		fontFamily: `Lato`,
		fontWeight: `normal`,
		fontStyle: `normal`,
	},
	headerTitleEtiquetaTripla: {
		color: `black`,
		fontSize: `6px`,
		height: `15px`,
		fontFamily: `Lato Bold`,
		fontWeight: `bold`,
		fontStyle: `normal`,
	},
	headerTitleEtiquetaSize: {
		color: `black`,
		fontSize: `7px`,
		height: `15px`,
		fontFamily: `Lato Bold`,
		fontWeight: `bold`,
		fontStyle: `normal`,
	},
	headerTitleEtiquetaSize3: {
		color: `black`,
		fontSize: `9px`,

		height: `11px`,
		fontFamily: `Lato Bold`,
		marginRight: `4px`,
		fontWeight: `bold`,
		fontStyle: `normal`,
	},
	headerLabel: {
		height: `13px`,
		color: `black`,
		fontSize: `8px`,
		marginLeft: `4px`,
		fontFamily: `Lato`,
		textTransform: `uppercase`,
		fontWeight: `normal`,
		width: `auto`,
	},
	headerLabel3: {
		height: `13px`,
		color: `black`,
		fontSize: `10px`,
		marginLeft: `4px`,
		fontFamily: `Lato`,
		textTransform: `uppercase`,
		fontWeight: `normal`,
		width: `auto`,
	},
	headerLabelSemUppercase: {
		height: `13px`,
		color: `black`,
		fontSize: `8px`,
		marginLeft: `4px`,
		fontFamily: `Lato`,
		fontWeight: `normal`,
		width: `auto`,
	},
	headerLabel1: {
		height: `14px`,
		color: `black`,
		fontSize: `9px`,
		marginLeft: `4px`,
		fontFamily: `Lato`,
		textTransform: `uppercase`,
		fontWeight: `normal`,
		width: `auto`,
	},
	headerLabelEtiqueta: {
		height: `14px`,
		color: `black`,
		fontSize: `7px`,
		marginLeft: `4px`,
		fontFamily: `Lato`,
		textTransform: `uppercase`,
		fontWeight: `normal`,
		width: `auto`,
	},
	headerLabelEtiquetaSolo: {
		height: `10px`,
		color: `black`,
		fontSize: `7px`,
		fontFamily: `Lato`,
		alignItems: `center`,
		textTransform: `uppercase`,
		fontWeight: `bold`,
		width: `auto`,
	},
	headerLabelEtiqueta3: {
		height: `11px`,
		color: `black`,
		fontSize: `9px`,
		marginLeft: `4px`,
		fontFamily: `Lato`,
		textTransform: `uppercase`,
		fontWeight: `normal`,
		width: `auto`,
	},
	headerLabelEtiqueta1: {
		height: `11px`,
		color: `black`,
		fontSize: `7px`,
		marginLeft: `4px`,
		fontFamily: `Lato`,
		textTransform: `uppercase`,
		fontWeight: `normal`,
		width: `auto`,
	},
}
const naoUsados = {
	itemContent: {
		display: `flex`,
		flexDirection: `column`,
		alignItems: `flex-start`,
		justifyContent: `space-between`,
	},
	bottomBorder: {
		borderBottomWidth: 1,
		borderBottomColor: `#516680`,
		borderBottomStyle: `solid`,
		borderRadius: `2%`,
	},
	bottomBorderBlack: {
		borderBottomWidth: 1,
		fontSize: `12px`,
		marginTop: `8px`,
		marginBottom: `12px`,
		paddingBottom: `5px`,
		borderBottomColor: `#000`,
		borderBottomStyle: `solid`,
		borderRadius: `2%`,
	},
	descricaoPlantao: {
		fontSize: `12px`,
	},
	detailColumn: {
		flexDirection: `column`,
		flexGrow: 9,
		textTransform: `uppercase`,
	},
	linkColumn: {
		flexDirection: `column`,
		flexGrow: 2,
		alignSelf: `flex-end`,
	},
	subtitle: {
		fontSize: 10,
		fontFamily: `Lato`,
	},
	link: {
		fontFamily: `Lato`,
		fontSize: 10,
		color: `black`,
		textDecoration: `none`,
		alignSelf: `flex-end`,
	},
	grid: {
		maxWidth: `400px`,
		margin: `0 auto`,
		border: `1px solid #ccc`,
	},
}
const linhaDeDados = {
	flexGrow1: {
		width: `10%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex10p: {
		width: `10%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex15p: {
		width: `15%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex20p: {
		width: `20%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex25p: {
		width: `25%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex30p: {
		width: `30%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex40p: {
		width: `40%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex45p: {
		width: `45%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex50p: {
		width: `50%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex60p: {
		width: `60%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex70p: {
		width: `70%`,
		height: `100%`,
		alignItems: `baseline`,
	},
	flex80p: {
		width: `80%`,

		height: `100%`,
		alignItems: `baseline`,
	},
	baseLine: {
		alignItems: `baseline`,
	},
	flexGrow2: {
		height: `100%`,
		width: `50%`,
		display: `flex`,
		textAlign: `justify`,
		alignItems: `baseline`,
	},
	flexGrow3: {
		height: `100%`,
		width: `40%`,
		justifyContent: `space-between`,
		alignItems: `baseline`,
	},
	itemRow: {
		fontSize: 12,
		fontFamily: `Lato`,
	},
	itemRow8: {
		fontSize: 8,
		fontFamily: `Lato`,
	},
	fonte10: {
		fontSize: 10,
	},
	borderBottom: {
		borderBottom: `2px solid black`,
	},
	borderTop: {
		borderTop: `2px solid black`,
	},
	itemHeader: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `18px`,
		justifyContent: `space-between`,
		fontSize: 16,
		//border: '1px solid orange',
		width: `100%`,
	},
	itemHeader2: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `18px`,
		fontSize: 16,
	},
	itemHeaderMin: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `18px`,
		justifyContent: `space-between`,
		fontFamily: `Lato Bold`,
		fontSize: 12,
		//border: '1px solid orange',
	},
	itemHeaderStronger: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `16px`,
		fontFamily: `Lato Bold`,
		fontWeight: `900`,
		color: `black`,
		justifyContent: `space-between`,
		fontSize: 16,
		//border: '1px solid orange',
		width: `100%`,
	},
	itemLabel: {
		fontFamily: `Lato`,
		fontSize: 12,
		color: `black`,
		textTransform: `uppercase`,
	},
	itemLabelTotal: {
		fontFamily: `Lato`,
		fontSize: 12,
		color: `black`,
	},
	itemHeaderStronger2: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `12px`,
		fontFamily: `Lato Bold`,
		fontWeight: `900`,
		color: `black`,
		justifyContent: `space-between`,
		fontSize: 12,
		//border: '1px solid orange',
		width: `100%`,
	},
}
export const styles = StyleSheet.create({
	...geral,
	...header,
	...naoUsados,
	...linhaDeDados,
	name: {
		fontSize: 24,
		fontFamily: `Lato Bold`,
		textAlign: `center`,
		alignSelf: `center`,
	},
	name18: {
		fontSize: 18,
		fontFamily: `Lato Bold`,
		textAlign: `center`,
		alignSelf: `center`,
	},
	name16: {
		fontSize: 16,
		fontFamily: `Lato Bold`,
		textAlign: `center`,
		alignSelf: `center`,
	},
	name15: {
		fontSize: 15,
		fontFamily: `Lato Bold`,
		textAlign: `center`,
		alignSelf: `center`,
	},
	name20: {
		fontSize: 20,
		fontFamily: `Lato Bold`,
		textAlign: `center`,
		alignSelf: `center`,
	},
	itemgrid: {
		margin: `5px`,
		//@ts-ignore
		background: `green`,
		textAlign: `center`,
		fontSize: `1.5em`,
	},
})
// @ts-ignore
export const stylesHeader2 = StyleSheet.create({
	...header,
	...geral,
	baseLine: {
		alignItems: `baseline`,
	},
	rowHeader2: {
		display: `flex`,
		flexDirection: `row`,
		alignItems: `baseline`,
		height: `16px`,
		justifyContent: `flex-start`,
		//border: '1px solid orange',
	},
	borderBottom: {
		borderBottom: `2px solid black`,
		padding: `0px 0px`,
	},
	fg5: {
		width: `41%`,
		// backgroundColor:`green`,
	},
	fg4: {
		width: `33%`,
		// backgroundColor:`red`
	},
	fg2: {
		width: `17%`,
		// backgroundColor:`blue`
	},
	fg3: {
		width: `25%`,
		// backgroundColor:`orange`
	},
})
