# Generated by Django 4.1.9 on 2023-06-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autoclavagem",
            fields=[
                (
                    "idautoclavagem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ciclo", models.IntegerField(blank=True, null=True)),
                ("datafim", models.DateTimeField(blank=True, null=True)),
                ("datainicio", models.DateTimeField()),
                (
                    "statusfim",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("statusinicio", models.CharField(max_length=20)),
                (
                    "tipolimpeza",
                    models.CharField(blank=True, max_length=99, null=True),
                ),
                ("dataabortado", models.DateTimeField(blank=True, null=True)),
                (
                    "statusabortado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "autoclavagem",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Caixa",
            fields=[
                (
                    "idcaixa",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
                (
                    "descricaoabreviado",
                    models.CharField(max_length=20, unique=True),
                ),
                ("mes", models.IntegerField()),
                ("temperatura", models.CharField(max_length=20)),
                ("criticidade", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "caixa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Caixavalor",
            fields=[
                (
                    "idcaixavalor",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90)),
                (
                    "valorcaixa",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "caixavalor",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "idcli",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "bairrocli",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                (
                    "cepcli",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "cidadecli",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                (
                    "cnpjcli",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "codigocli",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "contatocli",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("datacadastrocli", models.DateField()),
                (
                    "emailcli",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("horacadastrocli", models.TimeField()),
                (
                    "inscricaoestadualcli",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "inscricaomunicipalcli",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "nomeabreviado",
                    models.CharField(max_length=90, unique=True),
                ),
                ("nomecli", models.CharField(max_length=90, unique=True)),
                (
                    "nomefantasiacli",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                (
                    "numerocli",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "ruacli",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                (
                    "telefonecli",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "ufcli",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "cliente",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Complemento",
            fields=[
                (
                    "idcomplemento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "complemento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Distribuicao",
            fields=[
                (
                    "iddistribuicao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "datacancelamentodistribuicao",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("datadistribuicao", models.DateTimeField()),
                ("dtdistribuicao", models.DateField()),
                (
                    "numerocautela",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "distribuicao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "idequipamento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
            ],
            options={
                "db_table": "equipamento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "idgrupo",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=80, unique=True)),
                ("nome", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "db_table": "grupo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itemcaixa",
            fields=[
                (
                    "iditemcaixa",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("qtdcriticidade", models.IntegerField()),
                ("quantidade", models.IntegerField()),
                (
                    "valorunitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "idcaixa",
                    models.ForeignKey(
                        db_column="idcaixa",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.caixa",
                    ),
                ),
            ],
            options={
                "db_table": "itemcaixa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Locacao",
            fields=[
                (
                    "idlocacao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("datafim", models.DateField()),
                ("datainicio", models.DateField()),
                ("statuslocacao", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "locacao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Origem",
            fields=[
                (
                    "idorigem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
            ],
            options={
                "db_table": "origem",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Parametrizacao",
            fields=[
                (
                    "idparametrizacao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "emaildestino",
                    models.CharField(
                        blank=True, max_length=60, null=True, unique=True
                    ),
                ),
                (
                    "emailorigem",
                    models.CharField(
                        blank=True, max_length=60, null=True, unique=True
                    ),
                ),
                (
                    "envia",
                    models.CharField(
                        blank=True, max_length=3, null=True, unique=True
                    ),
                ),
                (
                    "ipdistribuicaos",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ipesterilizacao",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ipproducao",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "iprecebimento",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "iptermodesinfeccao",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "senhaemailorigem",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "ipesterilizacaofim",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "iptermodesinfeccaofim",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("hora", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "parametrizacao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Profissao",
            fields=[
                (
                    "idprofissao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
            ],
            options={
                "db_table": "profissao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Profissional",
            fields=[
                (
                    "idprofissional",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("atrelado", models.CharField(max_length=1)),
                (
                    "contato",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("coren", models.CharField(max_length=10)),
                ("cpf", models.CharField(max_length=12, unique=True)),
                ("dtadmissao", models.DateField()),
                ("dtcadastro", models.DateField()),
                ("dtdesligamento", models.DateField(blank=True, null=True)),
                ("dtnascimento", models.DateTimeField()),
                (
                    "email",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "matricula",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("nome", models.CharField(max_length=90)),
                ("rt", models.CharField(max_length=1)),
                ("sexo", models.CharField(max_length=2)),
                ("status", models.CharField(max_length=30)),
                (
                    "idprofissao",
                    models.ForeignKey(
                        db_column="idprofissao",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.profissao",
                    ),
                ),
            ],
            options={
                "db_table": "profissional",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Revinfo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("timestamp", models.BigIntegerField()),
                ("dt_registro", models.DateField(blank=True, null=True)),
                ("hr_registro", models.TimeField(blank=True, null=True)),
                (
                    "ip",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usuario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "revinfo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "idsetor",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
            ],
            options={
                "db_table": "setor",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Subtipoproduto",
            fields=[
                (
                    "idsubtipoproduto",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
                ("dtcadastro", models.DateTimeField()),
            ],
            options={
                "db_table": "subtipoproduto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tipocaixa",
            fields=[
                (
                    "idtipocaixa",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
            ],
            options={
                "db_table": "tipocaixa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tipopacote",
            fields=[
                (
                    "idtipopacote",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
                ("dtcadastro", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tipopacote",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "idusu",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("apelidousu", models.CharField(max_length=31, unique=True)),
                ("ativo", models.BooleanField()),
                ("datacadastrousu", models.DateTimeField()),
                ("senhausu", models.CharField(max_length=90)),
                (
                    "idprofissional",
                    models.ForeignKey(
                        db_column="idprofissional",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.profissional",
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Usuariosecundario",
            fields=[
                (
                    "idusuariosecundario",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "usuariosecundario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UsuarioGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.grupo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "usuario_grupo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ultrassonica",
            fields=[
                (
                    "idultrassonica",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ciclo", models.IntegerField(blank=True, null=True)),
                ("dataultrassonica", models.DateTimeField()),
                ("statusultrassonica", models.CharField(max_length=20)),
                (
                    "idusu",
                    models.ForeignKey(
                        db_column="idusu",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "ultrassonica",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Termodesinfeccao",
            fields=[
                (
                    "idtermodesinfeccao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ciclo", models.IntegerField(blank=True, null=True)),
                ("datafim", models.DateTimeField(blank=True, null=True)),
                ("datainicio", models.DateTimeField()),
                (
                    "statusfim",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("statusinicio", models.CharField(max_length=20)),
                (
                    "tipolimpeza",
                    models.CharField(blank=True, max_length=99, null=True),
                ),
                (
                    "statusabortado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("dataabortado", models.DateTimeField(blank=True, null=True)),
                (
                    "idequipamento",
                    models.ForeignKey(
                        db_column="idequipamento",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.equipamento",
                    ),
                ),
                (
                    "idusu",
                    models.ForeignKey(
                        db_column="idusu",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
                (
                    "idusuariosecundario",
                    models.ForeignKey(
                        blank=True,
                        db_column="idusuariosecundario",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuariosecundario",
                    ),
                ),
            ],
            options={
                "db_table": "termodesinfeccao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Sequenciaetiqueta",
            fields=[
                (
                    "idsequenciaetiqueta",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                (
                    "idcaixa",
                    models.ForeignKey(
                        db_column="idcaixa",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.caixa",
                    ),
                ),
            ],
            options={
                "db_table": "sequenciaetiqueta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Romaneio",
            fields=[
                (
                    "idromaneio",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("data", models.DateField(blank=True, null=True)),
                ("hora", models.TimeField(blank=True, null=True)),
                ("numerocautela", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                (
                    "idcli",
                    models.ForeignKey(
                        db_column="idcli",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "romaneio",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                (
                    "idrecebimento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "datacancelamento",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("datarecebimento", models.DateTimeField()),
                (
                    "observacao",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("statusrecebimento", models.CharField(max_length=20)),
                (
                    "idorigem",
                    models.ForeignKey(
                        blank=True,
                        db_column="idorigem",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.origem",
                    ),
                ),
                (
                    "idusu",
                    models.ForeignKey(
                        db_column="idusu",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "recebimento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Profissionallocado",
            fields=[
                (
                    "idprofissionallocado",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "idlocacao",
                    models.ForeignKey(
                        db_column="idlocacao",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.locacao",
                    ),
                ),
                (
                    "idprofissional",
                    models.ForeignKey(
                        db_column="idprofissional",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.profissional",
                    ),
                ),
            ],
            options={
                "db_table": "profissionallocado",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "idproduto",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=90, unique=True)),
                ("dtcadastro", models.DateTimeField()),
                ("embalagem", models.CharField(max_length=15)),
                ("status", models.CharField(max_length=15)),
                (
                    "idsubtipoproduto",
                    models.ForeignKey(
                        db_column="idsubtipoproduto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.subtipoproduto",
                    ),
                ),
                (
                    "idtipopacote",
                    models.ForeignKey(
                        db_column="idtipopacote",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.tipopacote",
                    ),
                ),
            ],
            options={
                "db_table": "produto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Producao",
            fields=[
                (
                    "idproducao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ciclo", models.IntegerField(blank=True, null=True)),
                (
                    "datacancelamento",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dataproducao", models.DateTimeField()),
                ("datavalidade", models.DateField()),
                (
                    "observacao",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("statusproducao", models.CharField(max_length=20)),
                (
                    "idusu",
                    models.ForeignKey(
                        db_column="idusu",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "producao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Plantao",
            fields=[
                (
                    "idplantao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("datacadastro", models.DateField()),
                ("datafechamento", models.DateField(blank=True, null=True)),
                ("descricaoaberto", models.TextField()),
                (
                    "descricaofechamento",
                    models.TextField(blank=True, null=True),
                ),
                ("grupousuario", models.CharField(max_length=60)),
                ("horacadastro", models.TimeField()),
                ("horafechamento", models.TimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=30)),
                (
                    "idprofissional",
                    models.ForeignKey(
                        db_column="idprofissional",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.profissional",
                    ),
                ),
            ],
            options={
                "db_table": "plantao",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="locacao",
            name="idsetor",
            field=models.ForeignKey(
                db_column="idsetor",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.setor",
            ),
        ),
        migrations.CreateModel(
            name="Lavagem",
            fields=[
                (
                    "idlavagem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("datalavagem", models.DateTimeField()),
                ("statuslavagem", models.CharField(max_length=20)),
                (
                    "idusu",
                    models.ForeignKey(
                        db_column="idusu",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "lavagem",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itensultrassonica",
            fields=[
                (
                    "iditensultrassonica",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
                (
                    "idultrassonica",
                    models.ForeignKey(
                        db_column="idultrassonica",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.ultrassonica",
                    ),
                ),
            ],
            options={
                "db_table": "itensultrassonica",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itenstermodesinfeccao",
            fields=[
                (
                    "iditenstermodesinfeccao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
                (
                    "idtermodesinfeccao",
                    models.ForeignKey(
                        db_column="idtermodesinfeccao",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.termodesinfeccao",
                    ),
                ),
            ],
            options={
                "db_table": "itenstermodesinfeccao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itenslavagem",
            fields=[
                (
                    "iditenslavagem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "idlavagem",
                    models.ForeignKey(
                        db_column="idlavagem",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.lavagem",
                    ),
                ),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
            ],
            options={
                "db_table": "itenslavagem",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itensautoclavagem",
            fields=[
                (
                    "iditensautoclavagem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "idautoclavagem",
                    models.ForeignKey(
                        db_column="idautoclavagem",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.autoclavagem",
                    ),
                ),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
            ],
            options={
                "db_table": "itensautoclavagem",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itemromaneio",
            fields=[
                (
                    "iditemromaneio",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "idromaneio",
                    models.ForeignKey(
                        db_column="idromaneio",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.romaneio",
                    ),
                ),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
            ],
            options={
                "db_table": "itemromaneio",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itemrecebimento",
            fields=[
                (
                    "iditemrecebimento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "iditemcaixa",
                    models.ForeignKey(
                        db_column="iditemcaixa",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.itemcaixa",
                    ),
                ),
                (
                    "idrecebimento",
                    models.ForeignKey(
                        db_column="idrecebimento",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.recebimento",
                    ),
                ),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
            ],
            options={
                "db_table": "itemrecebimento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itemproducao",
            fields=[
                (
                    "iditemproducao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "dataproducaodistribuicaosequencial",
                    models.DateField(blank=True, null=True),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "statusproducaodistribuicaosequencial",
                    models.BooleanField(),
                ),
                (
                    "iditemcaixa",
                    models.ForeignKey(
                        db_column="iditemcaixa",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.itemcaixa",
                    ),
                ),
                (
                    "idproducao",
                    models.ForeignKey(
                        db_column="idproducao",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.producao",
                    ),
                ),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
            ],
            options={
                "db_table": "itemproducao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Itemdistribuicao",
            fields=[
                (
                    "iditemdistribuicao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "idcli",
                    models.ForeignKey(
                        db_column="idcli",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.cliente",
                    ),
                ),
                (
                    "iddistribuicao",
                    models.ForeignKey(
                        db_column="iddistribuicao",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.distribuicao",
                    ),
                ),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
            ],
            options={
                "db_table": "itemdistribuicao",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="itemcaixa",
            name="idproduto",
            field=models.ForeignKey(
                db_column="idproduto",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.produto",
            ),
        ),
        migrations.CreateModel(
            name="Indicador",
            fields=[
                (
                    "idindicador",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("datalancamento", models.DateField()),
                (
                    "descricao",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                ("status", models.CharField(max_length=90)),
                (
                    "idusu",
                    models.ForeignKey(
                        db_column="idusu",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "indicador",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "idevento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "apelidousuarioprimario",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                ("ciclo", models.IntegerField(blank=True, null=True)),
                (
                    "datacancelamentodistribuicao",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "datacancelamentoproducao",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "datacancelamentorecebimento",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "datadistribuicao",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dataevento", models.DateField()),
                (
                    "datafimautoclavagem",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "datafimtermodesinfecao",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "datainicioautoclavagem",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "datainiciotermodesinfecao",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dataproducao", models.DateTimeField(blank=True, null=True)),
                (
                    "datarecebimento",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("descricaocaixa", models.CharField(max_length=90)),
                ("horaevento", models.TimeField()),
                ("idsequenciaetiqueta", models.CharField(max_length=255)),
                ("nomecliente", models.CharField(max_length=90)),
                ("status", models.CharField(max_length=90)),
                (
                    "datalancamento",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "idautoclavagem",
                    models.ForeignKey(
                        blank=True,
                        db_column="idautoclavagem",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.autoclavagem",
                    ),
                ),
                (
                    "iddistribuicao",
                    models.ForeignKey(
                        blank=True,
                        db_column="iddistribuicao",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.distribuicao",
                    ),
                ),
                (
                    "idlavagem",
                    models.ForeignKey(
                        blank=True,
                        db_column="idlavagem",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.lavagem",
                    ),
                ),
                (
                    "idproducao",
                    models.ForeignKey(
                        blank=True,
                        db_column="idproducao",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.producao",
                    ),
                ),
                (
                    "idrecebimento",
                    models.ForeignKey(
                        blank=True,
                        db_column="idrecebimento",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.recebimento",
                    ),
                ),
                (
                    "idtermodesinfeccao",
                    models.ForeignKey(
                        blank=True,
                        db_column="idtermodesinfeccao",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.termodesinfeccao",
                    ),
                ),
                (
                    "idultrassonica",
                    models.ForeignKey(
                        blank=True,
                        db_column="idultrassonica",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.ultrassonica",
                    ),
                ),
                (
                    "idusu",
                    models.ForeignKey(
                        blank=True,
                        db_column="idusu",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
                (
                    "idusuariosecundario",
                    models.ForeignKey(
                        blank=True,
                        db_column="idusuariosecundario",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuariosecundario",
                    ),
                ),
            ],
            options={
                "db_table": "evento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "idetiqueta",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("autoclave", models.IntegerField()),
                (
                    "biologico",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("ciclo", models.IntegerField()),
                ("datafabricacao", models.DateField()),
                ("datalancamento", models.DateField()),
                ("datavalidade", models.DateField()),
                ("horalancamento", models.TimeField()),
                ("numero", models.IntegerField()),
                ("numerofaltante", models.IntegerField()),
                (
                    "obs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "peso",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("qtd", models.IntegerField()),
                ("qtdimpressao", models.IntegerField()),
                ("seladora", models.CharField(max_length=20)),
                ("servico", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("temperatura", models.IntegerField(blank=True, null=True)),
                ("tipoetiqueta", models.CharField(max_length=20)),
                (
                    "totalenvelopado",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "idcli",
                    models.ForeignKey(
                        db_column="idcli",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.cliente",
                    ),
                ),
                (
                    "idcomplemento",
                    models.ForeignKey(
                        blank=True,
                        db_column="idcomplemento",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.complemento",
                    ),
                ),
                (
                    "idproduto",
                    models.ForeignKey(
                        db_column="idproduto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.produto",
                    ),
                ),
                (
                    "idprofissional",
                    models.ForeignKey(
                        db_column="idprofissional",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.profissional",
                    ),
                ),
            ],
            options={
                "db_table": "etiqueta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "idestoque",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("quantidade", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("datavalidade", models.DateField(blank=True, null=True)),
                (
                    "idsequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
            ],
            options={
                "db_table": "estoque",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="distribuicao",
            name="idusu",
            field=models.ForeignKey(
                db_column="idusu",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Diario",
            fields=[
                (
                    "iddiario",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("arquivo", models.TextField(blank=True, null=True)),
                ("dataabertura", models.DateField()),
                ("datafechamento", models.DateField(blank=True, null=True)),
                ("dataretroativa", models.DateField(blank=True, null=True)),
                ("descricaoaberto", models.TextField()),
                (
                    "descricaoacaoocorrencia",
                    models.TextField(blank=True, null=True),
                ),
                ("horaabertura", models.TimeField()),
                ("horafechamento", models.TimeField(blank=True, null=True)),
                ("horaretroativa", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("statusdiariodeocorrencia", models.CharField(max_length=30)),
                ("tipodediariodeocorrencia", models.CharField(max_length=30)),
                ("titulo", models.CharField(max_length=100)),
                (
                    "uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "idcli",
                    models.ForeignKey(
                        blank=True,
                        db_column="idcli",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.cliente",
                    ),
                ),
                (
                    "idindicador",
                    models.ForeignKey(
                        blank=True,
                        db_column="idindicador",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.indicador",
                    ),
                ),
                (
                    "idsetor",
                    models.ForeignKey(
                        db_column="idsetor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.setor",
                    ),
                ),
                (
                    "idusu",
                    models.ForeignKey(
                        db_column="idusu",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "diario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cautela",
            fields=[
                (
                    "idcautela",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("arquivo", models.TextField(blank=True, null=True)),
                ("dataabertura", models.DateField(blank=True, null=True)),
                ("datafechado", models.DateField(blank=True, null=True)),
                ("descricaoaberto", models.TextField()),
                (
                    "descricaofechamento",
                    models.TextField(blank=True, null=True),
                ),
                ("fator", models.IntegerField(blank=True, null=True)),
                ("horaabertura", models.TimeField(blank=True, null=True)),
                ("horadatafechado", models.TimeField(blank=True, null=True)),
                ("numero", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=30)),
                ("titulo", models.CharField(max_length=100)),
                (
                    "idcliente",
                    models.ForeignKey(
                        db_column="idcliente",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.cliente",
                    ),
                ),
                (
                    "idprofissional",
                    models.ForeignKey(
                        db_column="idprofissional",
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.profissional",
                    ),
                ),
                (
                    "idsetor",
                    models.ForeignKey(
                        db_column="idsetor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.setor",
                    ),
                ),
            ],
            options={
                "db_table": "cautela",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="caixa",
            name="idcaixavalor",
            field=models.ForeignKey(
                blank=True,
                db_column="idcaixavalor",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.caixavalor",
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="idcli",
            field=models.ForeignKey(
                db_column="idcli",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.cliente",
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="idtipocaixa",
            field=models.ForeignKey(
                db_column="idtipocaixa",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.tipocaixa",
            ),
        ),
        migrations.AddField(
            model_name="autoclavagem",
            name="idequipamento",
            field=models.ForeignKey(
                db_column="idequipamento",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.equipamento",
            ),
        ),
        migrations.AddField(
            model_name="autoclavagem",
            name="idusu",
            field=models.ForeignKey(
                blank=True,
                db_column="idusu",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.usuario",
            ),
        ),
        migrations.AddField(
            model_name="autoclavagem",
            name="idusuariosecundario",
            field=models.ForeignKey(
                blank=True,
                db_column="idusuariosecundario",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.usuariosecundario",
            ),
        ),
        migrations.CreateModel(
            name="UsuariosecundarioAud",
            fields=[
                (
                    "idusuariosecundario",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "usuariosecundario_aud",
                "managed": True,
                "unique_together": {("idusuariosecundario", "rev")},
            },
        ),
        migrations.CreateModel(
            name="UsuarioAud",
            fields=[
                (
                    "idusu",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "usuario_aud",
                "managed": True,
                "unique_together": {("idusu", "rev")},
            },
        ),
        migrations.CreateModel(
            name="UltrassonicaAud",
            fields=[
                (
                    "idultrassonica",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "ultrassonica_aud",
                "managed": True,
                "unique_together": {("idultrassonica", "rev")},
            },
        ),
        migrations.CreateModel(
            name="TipopacoteAud",
            fields=[
                (
                    "idtipopacote",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "tipopacote_aud",
                "managed": True,
                "unique_together": {("idtipopacote", "rev")},
            },
        ),
        migrations.CreateModel(
            name="TipocaixaAud",
            fields=[
                (
                    "idtipocaixa",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "tipocaixa_aud",
                "managed": True,
                "unique_together": {("idtipocaixa", "rev")},
            },
        ),
        migrations.CreateModel(
            name="TermodesinfeccaoAud",
            fields=[
                (
                    "idtermodesinfeccao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "termodesinfeccao_aud",
                "managed": True,
                "unique_together": {("idtermodesinfeccao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="SubtipoprodutoAud",
            fields=[
                (
                    "idsubtipoproduto",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "subtipoproduto_aud",
                "managed": True,
                "unique_together": {("idsubtipoproduto", "rev")},
            },
        ),
        migrations.CreateModel(
            name="SetorAud",
            fields=[
                (
                    "idsetor",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "setor_aud",
                "managed": True,
                "unique_together": {("idsetor", "rev")},
            },
        ),
        migrations.CreateModel(
            name="SequenciaetiquetaAud",
            fields=[
                (
                    "idsequenciaetiqueta",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "sequenciaetiqueta_aud",
                "managed": True,
                "unique_together": {("idsequenciaetiqueta", "rev")},
            },
        ),
        migrations.CreateModel(
            name="RomaneioAud",
            fields=[
                (
                    "idromaneio",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "romaneio_aud",
                "managed": True,
                "unique_together": {("idromaneio", "rev")},
            },
        ),
        migrations.CreateModel(
            name="RecebimentoAud",
            fields=[
                (
                    "idrecebimento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "recebimento_aud",
                "managed": True,
                "unique_together": {("idrecebimento", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ProfissionallocadoAud",
            fields=[
                (
                    "idprofissionallocado",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                ("idlocacao", models.BigIntegerField(blank=True, null=True)),
                (
                    "idprofissional",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "profissionallocado_aud",
                "managed": True,
                "unique_together": {("idprofissionallocado", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ProfissionalAud",
            fields=[
                (
                    "idprofissional",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "profissional_aud",
                "managed": True,
                "unique_together": {("idprofissional", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ProfissaoAud",
            fields=[
                (
                    "idprofissao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "profissao_aud",
                "managed": True,
                "unique_together": {("idprofissao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ProdutoAud",
            fields=[
                (
                    "idproduto",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "produto_aud",
                "managed": True,
                "unique_together": {("idproduto", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ProducaoAud",
            fields=[
                (
                    "idproducao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "producao_aud",
                "managed": True,
                "unique_together": {("idproducao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="PlantaoAud",
            fields=[
                (
                    "idplantao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                ("datacadastro", models.DateField(blank=True, null=True)),
                ("datafechamento", models.DateField(blank=True, null=True)),
                (
                    "grupousuario",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("horacadastro", models.TimeField(blank=True, null=True)),
                ("horafechamento", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "idprofissional",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "plantao_aud",
                "managed": True,
                "unique_together": {("idplantao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ParametrizacaoAud",
            fields=[
                (
                    "idparametrizacao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "parametrizacao_aud",
                "managed": True,
                "unique_together": {("idparametrizacao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="OrigemAud",
            fields=[
                (
                    "idorigem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "origem_aud",
                "managed": True,
                "unique_together": {("idorigem", "rev")},
            },
        ),
        migrations.CreateModel(
            name="LocacaoAud",
            fields=[
                (
                    "idlocacao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                ("datafim", models.DateField(blank=True, null=True)),
                ("datainicio", models.DateField(blank=True, null=True)),
                (
                    "statuslocacao",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "locacao_aud",
                "managed": True,
                "unique_together": {("idlocacao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="LavagemAud",
            fields=[
                (
                    "idlavagem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "lavagem_aud",
                "managed": True,
                "unique_together": {("idlavagem", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItensultrassonicaAud",
            fields=[
                (
                    "iditensultrassonica",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itensultrassonica_aud",
                "managed": True,
                "unique_together": {("iditensultrassonica", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItenstermodesinfeccaoAud",
            fields=[
                (
                    "iditenstermodesinfeccao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itenstermodesinfeccao_aud",
                "managed": True,
                "unique_together": {("iditenstermodesinfeccao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItenslavagemAud",
            fields=[
                (
                    "iditenslavagem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itenslavagem_aud",
                "managed": True,
                "unique_together": {("iditenslavagem", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItensautoclavagemAud",
            fields=[
                (
                    "iditensautoclavagem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itensautoclavagem_aud",
                "managed": True,
                "unique_together": {("iditensautoclavagem", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItemromaneioAud",
            fields=[
                (
                    "iditemromaneio",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itemromaneio_aud",
                "managed": True,
                "unique_together": {("iditemromaneio", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItemrecebimentoAud",
            fields=[
                (
                    "iditemrecebimento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itemrecebimento_aud",
                "managed": True,
                "unique_together": {("iditemrecebimento", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItemproducaoAud",
            fields=[
                (
                    "iditemproducao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itemproducao_aud",
                "managed": True,
                "unique_together": {("iditemproducao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItemdistribuicaoAud",
            fields=[
                (
                    "iditemdistribuicao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itemdistribuicao_aud",
                "managed": True,
                "unique_together": {("iditemdistribuicao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ItemcaixaAud",
            fields=[
                (
                    "iditemcaixa",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "itemcaixa_aud",
                "managed": True,
                "unique_together": {("iditemcaixa", "rev")},
            },
        ),
        migrations.CreateModel(
            name="IndicadorAud",
            fields=[
                (
                    "idindicador",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                ("idusu", models.BigIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "indicador_aud",
                "managed": True,
                "unique_together": {("idindicador", "rev")},
            },
        ),
        migrations.CreateModel(
            name="GrupoAud",
            fields=[
                (
                    "idgrupo",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "grupo_aud",
                "managed": True,
                "unique_together": {("idgrupo", "rev")},
            },
        ),
        migrations.CreateModel(
            name="EventoAud",
            fields=[
                (
                    "idevento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "datalancamento",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "evento_aud",
                "managed": True,
                "unique_together": {("idevento", "rev")},
            },
        ),
        migrations.CreateModel(
            name="EtiquetaAud",
            fields=[
                (
                    "idetiqueta",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "peso",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "etiqueta_aud",
                "managed": True,
                "unique_together": {("idetiqueta", "rev")},
            },
        ),
        migrations.CreateModel(
            name="EstoqueAud",
            fields=[
                (
                    "idestoque",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "estoque_aud",
                "managed": True,
                "unique_together": {("idestoque", "rev")},
            },
        ),
        migrations.CreateModel(
            name="EquipamentoAud",
            fields=[
                (
                    "idequipamento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "descricao",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "equipamento_aud",
                "managed": True,
                "unique_together": {("idequipamento", "rev")},
            },
        ),
        migrations.CreateModel(
            name="DistribuicaoAud",
            fields=[
                (
                    "iddistribuicao",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "distribuicao_aud",
                "managed": True,
                "unique_together": {("iddistribuicao", "rev")},
            },
        ),
        migrations.CreateModel(
            name="DiarioAud",
            fields=[
                (
                    "iddiario",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                ("arquivo", models.TextField(blank=True, null=True)),
                ("dataabertura", models.DateField(blank=True, null=True)),
                ("datafechamento", models.DateField(blank=True, null=True)),
                ("dataretroativa", models.DateField(blank=True, null=True)),
                ("descricaoaberto", models.TextField(blank=True, null=True)),
                (
                    "descricaoacaoocorrencia",
                    models.TextField(blank=True, null=True),
                ),
                ("horaabertura", models.TimeField(blank=True, null=True)),
                ("horafechamento", models.TimeField(blank=True, null=True)),
                ("horaretroativa", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "statusdiariodeocorrencia",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "tipodediariodeocorrencia",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("idcli", models.BigIntegerField(blank=True, null=True)),
                ("idsetor", models.BigIntegerField(blank=True, null=True)),
                ("idusu", models.BigIntegerField(blank=True, null=True)),
                ("idindicador", models.BigIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "diario_aud",
                "managed": True,
                "unique_together": {("iddiario", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ComplementoAud",
            fields=[
                (
                    "idcomplemento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "descricao",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "complemento_aud",
                "managed": True,
                "unique_together": {("idcomplemento", "rev")},
            },
        ),
        migrations.CreateModel(
            name="ClienteAud",
            fields=[
                (
                    "idcli",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "cliente_aud",
                "managed": True,
                "unique_together": {("idcli", "rev")},
            },
        ),
        migrations.CreateModel(
            name="CautelaAud",
            fields=[
                (
                    "idcautela",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                ("arquivo", models.TextField(blank=True, null=True)),
                ("dataabertura", models.DateField(blank=True, null=True)),
                ("datafechado", models.DateField(blank=True, null=True)),
                ("fator", models.IntegerField(blank=True, null=True)),
                ("horaabertura", models.TimeField(blank=True, null=True)),
                ("horadatafechado", models.TimeField(blank=True, null=True)),
                (
                    "numero",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("idcliente", models.BigIntegerField(blank=True, null=True)),
                (
                    "idprofissional",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("idsetor", models.BigIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "cautela_aud",
                "managed": True,
                "unique_together": {("idcautela", "rev")},
            },
        ),
        migrations.CreateModel(
            name="CaixavalorAud",
            fields=[
                (
                    "idcaixavalor",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "caixavalor_aud",
                "managed": True,
                "unique_together": {("idcaixavalor", "rev")},
            },
        ),
        migrations.CreateModel(
            name="CaixaAud",
            fields=[
                (
                    "idcaixa",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "caixa_aud",
                "managed": True,
                "unique_together": {("idcaixa", "rev")},
            },
        ),
        migrations.CreateModel(
            name="AutoclavagemAud",
            fields=[
                (
                    "idautoclavagem",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("revtype", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rev",
                    models.ForeignKey(
                        db_column="rev",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.revinfo",
                    ),
                ),
            ],
            options={
                "db_table": "autoclavagem_aud",
                "managed": True,
                "unique_together": {("idautoclavagem", "rev")},
            },
        ),
    ]
