# Generated by Django 4.1.9 on 2023-06-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissional",
            name="idprofissional",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="idusu",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
