# Generated by Django 4.1.9 on 2023-06-26 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0002_alter_usuario_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoEsterilizacaoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="updated_at",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Aguardando Coleta"),
                            ("PROCESSANDO", "Processando"),
                            ("PRONTO", "Em Arsenal"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADO", "Cancelado"),
                            ("TRANSPORTE", "Em Transporte"),
                        ],
                        default="PENDENTE",
                        max_length=255,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solicitacao_esterilizacao",
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoEsterilizacaoItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caixa",
                    models.ForeignKey(
                        db_column="sequenciaetiqueta_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.sequenciaetiqueta",
                    ),
                ),
                (
                    "solicitacao_esterilizacao",
                    models.ForeignKey(
                        db_column="solicitacao_esterilizacao_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="itens",
                        to="common.solicitacaoesterilizacaomodel",
                    ),
                ),
            ],
            options={
                "db_table": "solicitacao_esterilizacao_item",
            },
        ),
        migrations.CreateModel(
            name="HistoricoSolicitacaoEsterilizacaoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                (
                    "observacao",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "solicitacao_esterilizacao",
                    models.ForeignKey(
                        db_column="solicitacao_esterilizacao_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.solicitacaoesterilizacaomodel",
                    ),
                ),
            ],
            options={
                "db_table": "historico_solicitacao_esterilizacao",
            },
        ),
        migrations.CreateModel(
            name="ColetaEntregaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motorista", models.CharField(max_length=255)),
                ("veiculo", models.CharField(max_length=255)),
                (
                    "solicitacao_esterilizacao",
                    models.ForeignKey(
                        db_column="solicitacao_esterilizacao_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="coleta_entrega",
                        to="common.solicitacaoesterilizacaomodel",
                    ),
                ),
            ],
        ),
    ]
