# Generated by Django 4.1.9 on 2023-07-02 04:48

from django.db import migrations


def forwards_func(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT setval(pg_get_serial_sequence('profissional', 'idprofissional'), coalesce((SELECT MAX(idprofissional)+1 FROM profissional), 1), false);"
        )
        cursor.execute(
            "SELECT setval(pg_get_serial_sequence('usuario', 'idusu'), coalesce((SELECT MAX(idusu)+1 FROM usuario), 1), false);"
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_usuario_options_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
