# Generated by Django 4.1.9 on 2023-06-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_solicitacaoesterilizacaomodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicosolicitacaoesterilizacaomodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Aguardando Coleta"),
                    ("PROCESSANDO", "Processando"),
                    ("PRONTO", "Em Arsenal"),
                    ("ENTREGUE", "Entregue"),
                    ("CANCELADO", "Cancelado"),
                    ("TRANSPORTE", "Em Transporte"),
                ],
                default="PENDENTE",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicosolicitacaoesterilizacaomodel",
            name="solicitacao_esterilizacao",
            field=models.ForeignKey(
                db_column="solicitacao_esterilizacao_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="historico",
                to="common.solicitacaoesterilizacaomodel",
            ),
        ),
    ]
