# Generated by Django 4.1.9 on 2023-06-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_solicitacaoesterilizacaomodel_and_more"),
        ("common", "0003_veiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="coletaentregamodel",
            name="retorno",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="coletaentregamodel",
            name="motorista",
            field=models.ForeignKey(
                db_column="idprofissional",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.profissional",
            ),
        ),
        migrations.AlterField(
            model_name="coletaentregamodel",
            name="veiculo",
            field=models.ForeignKey(
                db_column="idveiculo",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.veiculo",
            ),
        ),
    ]
