# Generated by Django 4.1.9 on 2023-07-01 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_coletaentregamodel_retorno_and_more"),
        (
            "common",
            "0004_historicosolicitacaoesterilizacaomodel_status_and_more",
        ),
    ]

    operations = []
