# Generated by Django 4.1.9 on 2023-07-04 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_fix_tables_sequences"),
        ("common", "0005_merge_20230701_1653"),
    ]

    operations = []
