# Generated by Django 4.1.10 on 2023-07-05 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_merge_20230703_2305"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="coletaentregamodel",
            table="coleta_entrega",
        ),
    ]
