# Generated by Django 4.1.10 on 2023-07-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_coletaentregamodel_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="veiculo",
            old_name="idveiculo",
            new_name="id",
        ),
    ]
