# Generated by Django 4.1.10 on 2023-07-13 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_coletaentregamodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenciaetiqueta",
            name="idcaixa",
            field=models.ForeignKey(
                db_column="idcaixa",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="caixas",
                to="common.caixa",
            ),
        ),
    ]
