# Generated by Django 4.1.10 on 2023-07-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_rename_idveiculo_veiculo_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
