# Generated by Django 4.1.10 on 2023-07-14 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_auto_20230714_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenciaetiqueta",
            name="idcaixa",
            field=models.ForeignKey(
                db_column="idcaixa",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="caixas",
                to="common.caixa",
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="foto",
            field=models.ImageField(
                upload_to="veiculos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        message="Formato de imagem inválido. Utilize PNG, JPG ou JPEG.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="placa",
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "(^[a-zA-Z]{3}\\d{4}$)|(^[a-zA-Z]{3}\\d[a-zA-Z]\\d{2}$)",
                        message="Placa em formato inválido. Deve conter somente letras e números, no formato antigo ou novo (Mercosul).",
                    )
                ],
            ),
        ),
    ]
