# Generated by Django 4.1.10 on 2023-07-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_alter_usuariogrupo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissional",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                db_column="idcli",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="clientes",
                to="common.cliente",
            ),
        ),
    ]
