# Generated by Django 4.1.10 on 2023-07-14 15:56

from django.db import migrations
import re


def update_placa(apps, schema_editor):
    Veiculo = apps.get_model("common", "Veiculo")
    for veiculo in Veiculo.objects.all():
        veiculo.placa = re.sub(r"\W+", "", veiculo.placa)
        veiculo.placa = veiculo.placa.upper()
        if len(veiculo.placa) > 7:
            veiculo.placa = veiculo.placa[:7]
        veiculo.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_alter_veiculo_id"),
    ]

    operations = [
        migrations.RunPython(update_placa, reverse_code=reverse_func),
    ]
