# Generated by Django 4.1.10 on 2023-07-18 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_profissional_cliente"),
        ("common", "0012_veiculo_created_at_veiculo_created_by_and_more"),
    ]

    operations = []
