# Generated by Django 4.1.10 on 2023-07-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_merge_20230718_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coletaentregamodel",
            name="veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.veiculo",
            ),
        ),
    ]
