# Generated by Django 4.1.10 on 2023-08-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_cliente_created_at_cliente_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cepcli",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cnpjcli",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
