# Generated by Django 4.1.10 on 2023-08-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0016_alter_cliente_cepcli_alter_cliente_cnpjcli"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissional",
            name="cpf",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
