# Generated by Django 4.1.10 on 2023-08-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_alter_profissional_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="recebimento",
            name="solicitacao_esterilizacao_id",
            field=models.ForeignKey(
                blank=True,
                db_column="solicitacao_esterilizacao_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.solicitacaoesterilizacaomodel",
            ),
        ),
        migrations.AlterField(
            model_name="recebimento",
            name="statusrecebimento",
            field=models.CharField(max_length=30),
        ),
    ]
