# Generated by Django 4.1.10 on 2023-08-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0018_recebimento_solicitacao_esterilizacao_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recebimento",
            name="solicitacao_esterilizacao_id",
            field=models.ForeignKey(
                blank=True,
                db_column="solicitacao_esterilizacao_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="recebimentos",
                to="common.solicitacaoesterilizacaomodel",
            ),
        ),
    ]
