# Generated by Django 4.1.11 on 2023-09-05 00:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0019_alter_recebimento_solicitacao_esterilizacao_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caixa",
            old_name="idcli",
            new_name="cliente",
        ),
        migrations.RenameField(
            model_name="caixa",
            old_name="idcaixavalor",
            new_name="embalagem",
        ),
        migrations.AlterField(
            model_name="caixa",
            name="idcaixa",
            field=models.BigIntegerField(
                db_column="idcaixa", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="caixa",
            old_name="idcaixa",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="caixa",
            old_name="idtipocaixa",
            new_name="tipo_caixa",
        ),
        migrations.AddField(
            model_name="caixa",
            name="categoria_uso",
            field=models.IntegerField(
                choices=[
                    (1, "Cirurgia Cardíaca"),
                    (2, "Cirurgia Vascular"),
                    (3, "Cirurgia Geral"),
                    (4, "Cirurgia Neurológica"),
                    (5, "Cirurgia Ortopédica"),
                    (6, "Cirurgia Plástica"),
                    (7, "Emergência"),
                    (8, "Outros"),
                ],
                default=8,
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created_at",
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="desc",
            field=models.CharField(
                blank=True, db_column="desc", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="caixas",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        message="Formato de imagem inválido. Utilize PNG, JPG ou JPEG.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="instrucoes_uso",
            field=models.TextField(
                blank=True,
                help_text="Instruções para esterilização, armazenamento, uso e transporte.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="prioridade",
            field=models.IntegerField(
                choices=[
                    (1, "Urgente"),
                    (2, "Alta"),
                    (3, "Média"),
                    (4, "Baixa"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="situacao",
            field=models.IntegerField(
                choices=[(1, "Ativo"), (2, "Inativo"), (3, "Em Revisão")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="updated_at",
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="criticidade",
            field=models.IntegerField(
                choices=[
                    (1, "Não Crítico"),
                    (2, "Semicrítico"),
                    (3, "Crítico"),
                ],
                default=1,
                help_text="Nível de contato com o paciente.",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="descricao",
            field=models.CharField(
                db_column="descricao",
                help_text="Nome descritivo, deve ser único.",
                max_length=90,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O nome só pode conter letras maiúsculas, números e espaços.",
                        regex="^[A-Z0-9 ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="descricaoabreviado",
            field=models.CharField(
                db_column="descricaoabreviado",
                help_text="Código único do modelo, gerado automaticamente a partir do nome e não pode ser alterado. É utilizado como prefixo para a numeração das etiquetas.",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="mes",
            field=models.PositiveSmallIntegerField(
                db_column="mes",
                help_text="Validade do modelo de caixa em meses. Indique quantos meses o kit de esterilização permanece válido após ser preparado.",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="temperatura",
            field=models.CharField(
                help_text="Temperatura padrão de esterilização do modelo de caixa na autoclave (em graus Celsius).",
                max_length=20,
            ),
        ),
    ]
