# Generated by Django 4.1.10 on 2023-09-06 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0020_distribuicao_solicitacao_esterilizacao_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="capacidade",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created_at",
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="data_fabricacao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="fabricante",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="numero_serie",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="registro_anvisa",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="situacao",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="updated_at",
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
