# Generated by Django 4.1.10 on 2023-09-01 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_produto_created_at_produto_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produtos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        message="Formato de imagem inválido. Utilize PNG, JPG ou JPEG.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="situacao",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subtipoproduto",
            name="situacao",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tipopacote",
            name="situacao",
            field=models.BooleanField(default=True),
        ),
    ]
