# Generated by Django 4.1.11 on 2023-09-05 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_rename_idcli_caixa_cliente_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caixa",
            old_name="descricaoabreviado",
            new_name="codigo_modelo",
        ),
        migrations.RenameField(
            model_name="caixa",
            old_name="descricao",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="caixa",
            old_name="mes",
            new_name="validade",
        ),
    ]
