# Generated by Django 4.1.10 on 2023-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_distribuicao_solicitacao_esterilizacao_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="situacao",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
