# Generated by Django 4.1.11 on 2023-09-05 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0021_rename_descricaoabreviado_caixa_codigo_modelo_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="caixa",
            old_name="desc",
            new_name="descricao",
        ),
    ]
