# Generated by Django 4.1.10 on 2023-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_cliente_situacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="situacao",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
