# Generated by Django 4.1.11 on 2023-09-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_rename_desc_caixa_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="descricao",
            field=models.CharField(
                blank=True,
                db_column="desc",
                default="",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemcaixa",
            name="idcaixa",
            field=models.ForeignKey(
                db_column="idcaixa",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="itens",
                to="common.caixa",
            ),
        ),
    ]
