# Generated by Django 4.1.10 on 2023-09-13 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_alter_cliente_situacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="situacao",
            new_name="ativo",
        ),
    ]
