# Generated by Django 4.1.11 on 2023-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0023_alter_caixa_descricao_alter_itemcaixa_idcaixa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixavalor",
            name="idcaixavalor",
            field=models.BigIntegerField(
                db_column="idcaixavalor", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="caixavalor",
            old_name="idcaixavalor",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="tipocaixa",
            name="idtipocaixa",
            field=models.BigIntegerField(
                db_column="idtipocaixa", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="tipocaixa",
            old_name="idtipocaixa",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="caixa",
            name="temperatura",
            field=models.CharField(
                choices=[(121, "121°C"), (134, "134°C")],
                default=121,
                help_text="Temperatura padrão de esterilização do modelo de caixa na autoclave (em graus Celsius).",
                max_length=20,
            ),
        ),
    ]
