# Generated by Django 4.1.10 on 2023-09-06 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_distribuicao_solicitacao_esterilizacao_id"),
        (
            "common",
            "0023_tipopacote_created_at_tipopacote_created_by_and_more",
        ),
    ]

    operations = []
