# Generated by Django 4.1.11 on 2023-09-14 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0023_rename_situacao_cliente_ativo"),
        ("common", "0024_merge_20230906_1453"),
    ]

    operations = []
