# Generated by Django 4.1.11 on 2023-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0024_alter_caixavalor_idcaixavalor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="prioridade",
            field=models.IntegerField(
                choices=[
                    (1, "Urgente"),
                    (2, "Alta"),
                    (3, "Média"),
                    (4, "Baixa"),
                ],
                default=3,
                help_text="Prioridade de esterilização. Apenas informativo, não afeta o funcionamento do sistema.",
            ),
        ),
    ]
