# Generated by Django 4.1.11 on 2023-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0025_alter_caixa_prioridade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixavalor",
            name="id",
            field=models.BigAutoField(
                db_column="idcaixavalor", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tipocaixa",
            name="id",
            field=models.BigAutoField(
                db_column="idtipocaixa", primary_key=True, serialize=False
            ),
        ),
    ]
