# Generated by Django 4.1.10 on 2023-09-14 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0021_equipamento_capacidade_equipamento_created_at_and_more",
        ),
        ("common", "0025_merge_20230914_1648"),
    ]

    operations = []
