# Generated by Django 4.1.11 on 2023-09-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0026_alter_caixavalor_id_alter_tipocaixa_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcaixa",
            name="iditemcaixa",
            field=models.BigIntegerField(
                db_column="iditemcaixa", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="itemcaixa",
            old_name="iditemcaixa",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="caixa",
            name="id",
            field=models.BigAutoField(
                db_column="idcaixa", primary_key=True, serialize=False
            ),
        ),
    ]
