# Generated by Django 4.1.11 on 2023-09-14 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0025_alter_caixa_prioridade"),
        ("common", "0026_alter_usuario_idprofissional"),
        ("common", "0027_rename_situacao_equipamento_ativo_and_more"),
    ]

    operations = []
