# Generated by Django 4.1.11 on 2023-09-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0027_alter_itemcaixa_iditemcaixa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcaixa",
            name="id",
            field=models.BigAutoField(
                db_column="iditemcaixa", primary_key=True, serialize=False
            ),
        ),
    ]
