# Generated by Django 4.1.11 on 2023-09-12 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0028_alter_itemcaixa_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemcaixa",
            old_name="idcaixa",
            new_name="caixa",
        ),
    ]
