# Generated by Django 4.1.11 on 2023-09-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_rename_idcaixa_itemcaixa_caixa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caixa",
            options={
                "managed": True,
                "verbose_name": "Modelo de Caixa",
                "verbose_name_plural": "Modelos de Caixa",
            },
        ),
        migrations.RenameField(
            model_name="itemcaixa",
            old_name="idproduto",
            new_name="produto",
        ),
        migrations.AlterField(
            model_name="caixa",
            name="temperatura",
            field=models.CharField(
                choices=[("121", "121°C"), ("134", "134°C")],
                default="121",
                help_text="Temperatura padrão de esterilização do modelo de caixa na autoclave (em graus Celsius).",
                max_length=20,
            ),
        ),
    ]
