# Generated by Django 4.1.11 on 2023-09-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0030_alter_caixa_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcaixa",
            name="valorunitario",
            field=models.DecimalField(
                db_column="valorunitario", decimal_places=2, max_digits=10
            ),
        ),
        migrations.RenameField(
            model_name="itemcaixa",
            old_name="valorunitario",
            new_name="valor_unitario",
        ),
        migrations.AlterField(
            model_name="itemcaixa",
            name="produto",
            field=models.ForeignKey(
                db_column="idproduto",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="itens",
                to="common.produto",
            ),
        ),
    ]
