# Generated by Django 4.1.11 on 2023-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0031_alter_itemcaixa_valorunitario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcaixa",
            name="qtdcriticidade",
            field=models.IntegerField(db_column="qtdcriticidade"),
        ),
        migrations.RenameField(
            model_name="itemcaixa",
            old_name="qtdcriticidade",
            new_name="criticidade",
        ),
    ]
