# Generated by Django 4.1.11 on 2023-09-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0033_alter_itemcaixa_criticidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcaixa",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
    ]
