# Generated by Django 4.1.11 on 2023-09-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0035_alter_itemcaixa_quantidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="criticidade",
            field=models.IntegerField(
                choices=[
                    (1, "Não Crítico"),
                    (2, "Semicrítico"),
                    (3, "Crítico"),
                ],
                help_text="Nível de contato com o paciente.",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="temperatura",
            field=models.CharField(
                choices=[("121", "121°C"), ("134", "134°C")],
                help_text="Temperatura padrão de esterilização do modelo de caixa na autoclave (em graus Celsius).",
                max_length=20,
            ),
        ),
    ]
