# Generated by Django 4.1.11 on 2023-09-14 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0036_alter_caixa_criticidade_alter_caixa_temperatura"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemcaixa",
            options={
                "managed": True,
                "verbose_name": "Item de Caixa",
                "verbose_name_plural": "Itens de Caixa",
            },
        ),
    ]
