# Generated by Django 4.1.11 on 2023-09-18 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0028_merge_20230914_2051"),
        ("common", "0038_merge_20230914_2025"),
    ]

    operations = []
