# Generated by Django 4.1.11 on 2023-09-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0040_caixavalor_created_at_caixavalor_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caixavalor",
            options={
                "managed": True,
                "verbose_name": "Embalagem",
                "verbose_name_plural": "Embalagens",
            },
        ),
        migrations.AlterModelOptions(
            name="tipocaixa",
            options={
                "managed": True,
                "verbose_name": "Tipo de caixa",
                "verbose_name_plural": "Tipos de caixa",
            },
        ),
        migrations.AlterField(
            model_name="itemcaixa",
            name="caixa",
            field=models.ForeignKey(
                db_column="idcaixa",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="common.caixa",
            ),
        ),
    ]
