# Generated by Django 4.1.11 on 2023-09-20 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0029_alter_caixa_created_at_alter_caixa_updated_at_and_more",
        ),
        (
            "common",
            "0041_alter_caixavalor_options_alter_tipocaixa_options_and_more",
        ),
    ]

    operations = []
