# Generated by Django 4.1.11 on 2023-09-19 17:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0042_merge_20230919_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clientes",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        message="Formato de imagem inválido. Utilize PNG, JPG ou JPEG.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="caixavalor",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                null=True,
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="caixavalor",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                null=True,
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="tipocaixa",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                null=True,
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="tipocaixa",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                null=True,
                verbose_name="updated_at",
            ),
        ),
    ]
