# Generated by Django 4.1.11 on 2023-09-20 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_alter_caixavalor_created_at_and_more"),
        ("common", "0043_cliente_foto_alter_caixavalor_created_at_and_more"),
    ]

    operations = []
