# Generated by Django 4.1.11 on 2023-09-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_profissao_created_at_profissao_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profissao",
            options={
                "managed": True,
                "verbose_name": "Profissão",
                "verbose_name_plural": "Profissões",
            },
        ),
        migrations.AlterModelOptions(
            name="setor",
            options={
                "managed": True,
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
            },
        ),
        migrations.AlterField(
            model_name="profissao",
            name="idprofissao",
            field=models.BigAutoField(
                db_column="idprofissao", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="profissao",
            old_name="idprofissao",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="setor",
            name="idsetor",
            field=models.BigAutoField(
                db_column="idsetor", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="setor",
            old_name="idsetor",
            new_name="id",
        ),
    ]
