# Generated by Django 4.1.11 on 2023-09-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_alter_caixavalor_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="categoria_uso",
            field=models.IntegerField(
                choices=[
                    (1, "Cirurgia Cardíaca"),
                    (2, "Cirurgia Vascular"),
                    (3, "Cirurgia Geral"),
                    (4, "Cirurgia Neurológica"),
                    (5, "Cirurgia Ortopédica"),
                    (6, "Cirurgia Plástica"),
                    (7, "Emergência"),
                    (8, "Outros"),
                ],
                default=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="criticidade",
            field=models.IntegerField(
                choices=[
                    (1, "Não Crítico"),
                    (2, "Semicrítico"),
                    (3, "Crítico"),
                ],
                help_text="Nível de contato com o paciente.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="prioridade",
            field=models.IntegerField(
                choices=[
                    (1, "Urgente"),
                    (2, "Alta"),
                    (3, "Média"),
                    (4, "Baixa"),
                ],
                default=3,
                help_text="Prioridade de esterilização. Apenas informativo, não afeta o funcionamento do sistema.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="situacao",
            field=models.IntegerField(
                choices=[(1, "Ativo"), (2, "Inativo"), (3, "Em Revisão")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="ativo",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="ativo",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="situacao",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="subtipoproduto",
            name="situacao",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="tipopacote",
            name="situacao",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
