# Generated by Django 4.1.11 on 2023-09-20 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0044_alter_caixa_categoria_uso_alter_caixa_criticidade_and_more",
        ),
        ("common", "0044_merge_20230920_1719"),
    ]

    operations = []
