# Generated by Django 4.1.11 on 2023-09-20 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0044_alter_profissao_options_alter_setor_options_and_more",
        ),
        ("common", "0045_merge_20230920_1952"),
    ]

    operations = []
