# Generated by Django 4.1.11 on 2023-10-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0046_merge_20230920_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariogrupo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
