# Generated by Django 4.1.11 on 2023-10-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0046_merge_20230920_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissional",
            name="coren",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
