# Generated by Django 4.1.11 on 2023-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0046_merge_20230920_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequenciaetiqueta",
            name="recebimento",
            field=models.ManyToManyField(to="common.recebimento"),
        ),
    ]
