# Generated by Django 4.1.12 on 2023-10-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0046_merge_20230920_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcaixa",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
