# Generated by Django 4.1.11 on 2023-09-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0046_merge_20230920_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="motorista_atual",
            field=models.ForeignKey(
                blank=True,
                db_column="idprofissional",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.profissional",
            ),
        ),
    ]
