# Generated by Django 4.1.11 on 2023-09-22 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0047_veiculo_motorista_atual"),
    ]

    operations = [
        migrations.AddField(
            model_name="coletaentregamodel",
            name="motorista_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coletaentregamodel",
            name="motorista",
            field=models.ForeignKey(
                db_column="idprofissional",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.profissional",
            ),
        ),
    ]
