# Generated by Django 4.1.11 on 2023-09-22 20:40

from django.db import migrations, transaction


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0048_coletaentregamodel_motorista_user"),
    ]

    @transaction.atomic
    def forwards_func(apps, schema_editor):
        ColetaEntregaModel = apps.get_model("common", "ColetaEntregaModel")
        User = apps.get_model("users", "User")
        for coleta_entrega in ColetaEntregaModel.objects.all():
            coleta_entrega.motorista_user = User.objects.filter(
                idprofissional=coleta_entrega.motorista
            ).first()
            coleta_entrega.save()

    @transaction.atomic
    def backwards_func(apps, schema_editor):
        ColetaEntregaModel = apps.get_model("common", "ColetaEntregaModel")

        for coleta_entrega in ColetaEntregaModel.objects.all():
            coleta_entrega.motorista = (
                coleta_entrega.motorista_user.idprofissional
            )
            coleta_entrega.save()

        ColetaEntregaModel.objects.all().update(motorista_user=None)

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
