# Generated by Django 4.1.12 on 2023-10-09 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0047_alter_usuariogrupo_id"),
        ("common", "0048_alter_itemcaixa_deleted"),
    ]

    operations = []
