# Generated by Django 4.1.11 on 2023-09-22 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0049_auto_20230922_1740"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coletaentregamodel",
            name="motorista",
        ),
    ]
