# Generated by Django 4.1.11 on 2023-09-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0051_rename_motorista_user_coletaentregamodel_motorista"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="motorista_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
