# Generated by Django 4.1.11 on 2023-10-10 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0047_sequenciaetiqueta_recebimento"),
        ("common", "0049_merge_20231009_1211"),
        ("common", "0052_alter_veiculo_motorista_atual"),
    ]

    operations = []
