# Generated by Django 4.1.12 on 2023-10-10 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0053_merge_20231010_1143"),
        ("common", "0053_merge_20231010_1153"),
    ]

    operations = []
