# Generated by Django 4.1.12 on 2023-10-18 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0054_merge_20231010_1444"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="caixas",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        message="Formato de imagem inválido. Utilize PNG ou JPG/JPEG.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="prioridade",
            field=models.IntegerField(
                choices=[
                    (1, "Urgente"),
                    (2, "Alta"),
                    (3, "Média"),
                    (4, "Baixa"),
                ],
                default=3,
                help_text="Prioridade de esterilização. Apenas informativo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clientes",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        message="Formato de imagem inválido. Utilize PNG, JPG/JPEG.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produtos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        message="Formato de imagem inválido. Utilize PNG ou JPG/JPEG.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="foto",
            field=models.ImageField(
                upload_to="veiculos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"],
                        message="Formato de imagem inválido. Utilize PNG ou JPG/JPEG.",
                    )
                ],
            ),
        ),
    ]
