# Generated by Django 4.1.12 on 2023-10-20 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0048_plantao_created_at_plantao_created_by_and_more"),
        ("common", "0055_alter_caixa_imagem_alter_caixa_prioridade_and_more"),
    ]

    operations = []
