# Generated by Django 4.1.12 on 2023-10-20 22:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_motorista"),
        ("common", "0055_alter_caixa_imagem_alter_caixa_prioridade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coleta",
            fields=[],
            options={
                "verbose_name": "Coleta",
                "verbose_name_plural": "Coletas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.coletaentregamodel",),
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.coletaentregamodel",),
        ),
        migrations.AlterModelOptions(
            name="veiculo",
            options={
                "managed": True,
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
            },
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="motorista_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.motorista",
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="placa",
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "(^[a-zA-Z]{3}\\d{4}$)|(^[a-zA-Z]{3}\\d[a-zA-Z]\\d{2}$)",
                        message="Placa em formato inválido. Deve conter somente letras e números, no formato antigo (ABC1234) ou novo (Mercosul - ABC1D23).",
                    )
                ],
            ),
        ),
    ]
