# Generated by Django 4.1.12 on 2023-10-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0056_merge_20231020_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantao",
            name="duracao",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
