# Generated by Django 4.1.12 on 2023-10-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_motorista"),
        ("common", "0056_coleta_entrega_alter_veiculo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coletaentregamodel",
            name="motorista",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.motorista",
            ),
        ),
    ]
