# Generated by Django 4.1.12 on 2023-10-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0057_alter_coletaentregamodel_motorista"),
    ]

    operations = [
        migrations.AddField(
            model_name="coletaentregamodel",
            name="situacao",
            field=models.IntegerField(
                choices=[
                    (0, "Não Iniciado"),
                    (1, "Em Andamento"),
                    (2, "Finalizado"),
                ],
                default=0,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="coletaentregamodel",
            name="veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="coletaentregas",
                to="common.veiculo",
            ),
        ),
    ]
