# Generated by Django 4.1.12 on 2023-10-30 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0057_itensautoclavagem_created_at_and_more"),
        ("common", "0058_coletaentregamodel_situacao_and_more"),
    ]

    operations = []
