# Generated by Django 4.1.12 on 2023-10-30 02:23

from django.db import migrations
from common.models import Grupo


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        Group = apps.get_model("auth", "Group")
        # Grupo = apps.get_model("common", "Grupo")

        group_names = [
            "TECNICORECEBIMENTO",
            "TECNICOTERMO",
            "TECNICOEMBALAGEM",
            "TECNICOESTERILIZACAO",
            "TECNICODISTRIBUICAO",
            "ENFERMAGEM",
            "ADMINISTRATIVO",
            "SUPERVISAOENFERMAGEM",
            "TECNICOENFERMAGEM",
            "ADMINISTRADORES",
            "LIDER_MOTORISTA",
            "SUPERVISOR_LOGISTICA",
        ]

        for group_name in group_names:
            Group.objects.get_or_create(name=group_name)

            try:
                Grupo.objects.get(nome=group_name)
            except Grupo.DoesNotExist:
                Grupo.objects.create(nome=group_name, descricao=group_name)

    def backwards_func(apps, schema_editor):
        Group = apps.get_model("auth", "Group")
        Grupo = apps.get_model("common", "Grupo")

        group_names = [
            "TECNICORECEBIMENTO",
            "TECNICOTERMO",
            "TECNICOEMBALAGEM",
            "TECNICOESTERILIZACAO",
            "TECNICODISTRIBUICAO",
            "ENFERMAGEM",
            "ADMINISTRATIVO",
            "SUPERVISAOENFERMAGEM",
            "TECNICOENFERMAGEM",
            "ADMINISTRADORES",
            "LIDER_MOTORISTA",
            "SUPERVISOR_LOGISTICA",
        ]

        for group_name in group_names:
            try:
                group = Group.objects.get(name=group_name)
                group.delete()
                grupo = Grupo.objects.get(nome=group_name)
                grupo.delete()
            except Group.DoesNotExist:
                pass

    dependencies = [
        ("common", "0058_coletaentregamodel_situacao_and_more"),
        ("common", "0103_alter_grupo_idgrupo"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
