# Generated by Django 4.1.12 on 2023-11-01 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0058_auto_20231031_0935"),
        ("common", "0059_auto_20231029_2323"),
    ]

    operations = []
