# Generated by Django 4.1.13 on 2023-11-07 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0060_evento_created_at_evento_created_by_and_more"),
        (
            "common",
            "0060_merge_0058_auto_20231031_0935_0059_auto_20231029_2323",
        ),
    ]

    operations = []
