# Generated by Django 4.1.12 on 2023-11-06 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0060_merge_0058_auto_20231031_0935_0059_auto_20231029_2323",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autoclavagem",
            options={
                "managed": True,
                "verbose_name": "Ciclo de Autoclavagem",
                "verbose_name_plural": "Ciclos de Autoclavagem",
            },
        ),
        migrations.AlterModelOptions(
            name="cautela",
            options={
                "managed": True,
                "verbose_name": "Cautela",
                "verbose_name_plural": "Cautelas",
            },
        ),
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "managed": True,
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="coletaentregamodel",
            options={
                "verbose_name": "Coleta/Entrega",
                "verbose_name_plural": "Coletas/Entregas",
            },
        ),
        migrations.AlterModelOptions(
            name="complemento",
            options={
                "managed": True,
                "verbose_name": "Complemento",
                "verbose_name_plural": "Complementos",
            },
        ),
        migrations.AlterModelOptions(
            name="diario",
            options={
                "managed": True,
                "verbose_name": "Diário de Ocorrências",
                "verbose_name_plural": "Diários de Ocorrências",
            },
        ),
        migrations.AlterModelOptions(
            name="distribuicao",
            options={
                "managed": True,
                "verbose_name": "Distribuição",
                "verbose_name_plural": "Distribuições",
            },
        ),
        migrations.AlterModelOptions(
            name="equipamento",
            options={
                "managed": True,
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="estoque",
            options={
                "managed": True,
                "verbose_name": "Estoque",
                "verbose_name_plural": "Estoques",
            },
        ),
        migrations.AlterModelOptions(
            name="etiqueta",
            options={
                "managed": True,
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
            },
        ),
        migrations.AlterModelOptions(
            name="evento",
            options={
                "managed": True,
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="grupo",
            options={
                "managed": True,
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
            },
        ),
        migrations.AlterModelOptions(
            name="historicosolicitacaoesterilizacaomodel",
            options={
                "verbose_name": "Histórico de Solicitação de Esterilização",
                "verbose_name_plural": "Históricos de Solicitação de Esterilização",
            },
        ),
        migrations.AlterModelOptions(
            name="indicador",
            options={
                "managed": True,
                "verbose_name": "Indicador",
                "verbose_name_plural": "Indicadores",
            },
        ),
        migrations.AlterModelOptions(
            name="itemdistribuicao",
            options={
                "managed": True,
                "verbose_name": "Item de Distribuição",
                "verbose_name_plural": "Itens de Distribuição",
            },
        ),
        migrations.AlterModelOptions(
            name="itemproducao",
            options={
                "managed": True,
                "verbose_name": "Item de Produção",
                "verbose_name_plural": "Itens de Produção",
            },
        ),
        migrations.AlterModelOptions(
            name="itemrecebimento",
            options={
                "managed": True,
                "verbose_name": "Item de Recebimento",
                "verbose_name_plural": "Itens de Recebimento",
            },
        ),
        migrations.AlterModelOptions(
            name="itemromaneio",
            options={
                "managed": True,
                "verbose_name": "Item de Romaneio",
                "verbose_name_plural": "Itens de Romaneio",
            },
        ),
        migrations.AlterModelOptions(
            name="itensautoclavagem",
            options={
                "managed": True,
                "verbose_name": "Item de Autoclavagem",
                "verbose_name_plural": "Itens de Autoclavagem",
            },
        ),
        migrations.AlterModelOptions(
            name="itenslavagem",
            options={
                "managed": True,
                "verbose_name": "Item de Lavagem",
                "verbose_name_plural": "Itens de Lavagem",
            },
        ),
        migrations.AlterModelOptions(
            name="itenstermodesinfeccao",
            options={
                "managed": True,
                "verbose_name": "Item de Termodesinfecção",
                "verbose_name_plural": "Itens de Termodesinfecção",
            },
        ),
        migrations.AlterModelOptions(
            name="itensultrassonica",
            options={
                "managed": True,
                "verbose_name": "Item de Ultrassônica",
                "verbose_name_plural": "Itens de Ultrassônica",
            },
        ),
        migrations.AlterModelOptions(
            name="lavagem",
            options={
                "managed": True,
                "verbose_name": "Lavagem",
                "verbose_name_plural": "Lavagens",
            },
        ),
        migrations.AlterModelOptions(
            name="locacao",
            options={
                "managed": True,
                "verbose_name": "Locação",
                "verbose_name_plural": "Locações",
            },
        ),
        migrations.AlterModelOptions(
            name="origem",
            options={
                "managed": True,
                "verbose_name": "Origem",
                "verbose_name_plural": "Origens",
            },
        ),
        migrations.AlterModelOptions(
            name="parametrizacao",
            options={
                "managed": True,
                "verbose_name": "Parametrização",
                "verbose_name_plural": "Parametrizações",
            },
        ),
        migrations.AlterModelOptions(
            name="plantao",
            options={
                "managed": True,
                "verbose_name": "Plantão",
                "verbose_name_plural": "Plantões",
            },
        ),
        migrations.AlterModelOptions(
            name="producao",
            options={
                "managed": True,
                "verbose_name": "Produção",
                "verbose_name_plural": "Produções",
            },
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={
                "managed": True,
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AlterModelOptions(
            name="profissional",
            options={
                "managed": True,
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
            },
        ),
        migrations.AlterModelOptions(
            name="profissionallocado",
            options={
                "managed": True,
                "verbose_name": "Locação de Profissional",
                "verbose_name_plural": "Locações de Profissionais",
            },
        ),
        migrations.AlterModelOptions(
            name="recebimento",
            options={
                "managed": True,
                "verbose_name": "Recebimento",
                "verbose_name_plural": "Recebimentos",
            },
        ),
        migrations.AlterModelOptions(
            name="revinfo",
            options={
                "managed": True,
                "verbose_name": "Revinfo",
                "verbose_name_plural": "Revinfos",
            },
        ),
        migrations.AlterModelOptions(
            name="romaneio",
            options={
                "managed": True,
                "verbose_name": "Romaneio",
                "verbose_name_plural": "Romaneios",
            },
        ),
        migrations.AlterModelOptions(
            name="sequenciaetiqueta",
            options={
                "managed": True,
                "verbose_name": "Serial",
                "verbose_name_plural": "Seriais",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitacaoesterilizacaoitemmodel",
            options={
                "verbose_name": "Item de Solicitação de Esterilização",
                "verbose_name_plural": "Itens de Solicitação de Esterilização",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitacaoesterilizacaomodel",
            options={
                "verbose_name": "Solicitação de Esterilização",
                "verbose_name_plural": "Solicitações de Esterilização",
            },
        ),
        migrations.AlterModelOptions(
            name="subtipoproduto",
            options={
                "managed": True,
                "verbose_name": "Subtipo de produto",
                "verbose_name_plural": "Subtipos de produto",
            },
        ),
        migrations.AlterModelOptions(
            name="termodesinfeccao",
            options={
                "managed": True,
                "verbose_name": "Termodesinfecção",
                "verbose_name_plural": "Termodesinfecções",
            },
        ),
        migrations.AlterModelOptions(
            name="tipopacote",
            options={
                "managed": True,
                "verbose_name": "Tipo de pacote",
                "verbose_name_plural": "Tipos de pacote",
            },
        ),
        migrations.AlterModelOptions(
            name="ultrassonica",
            options={
                "managed": True,
                "verbose_name": "Ultrassônica",
                "verbose_name_plural": "Ultrassônicas",
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "managed": True,
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.AlterModelOptions(
            name="usuariogrupo",
            options={
                "managed": True,
                "verbose_name": "Usuário vs Grupo",
                "verbose_name_plural": "Usuários vs Grupos",
            },
        ),
        migrations.AlterModelOptions(
            name="usuariosecundario",
            options={
                "managed": True,
                "verbose_name": "Usuário secundário",
                "verbose_name_plural": "Usuários secundários",
            },
        ),
    ]
