# Generated by Django 4.1.12 on 2023-11-06 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0062_alter_autoclavagem_options_alter_cautela_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="idproducao",
            new_name="preparo",
        ),
    ]
