# Generated by Django 4.1.13 on 2023-11-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0062_etiqueta_created_at_etiqueta_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etiqueta",
            name="numero",
            field=models.IntegerField(db_column="numero"),
        ),
        migrations.RenameField(
            model_name="etiqueta",
            old_name="numero",
            new_name="cautela",
        ),
        migrations.AlterField(
            model_name="etiqueta",
            name="idetiqueta",
            field=models.BigIntegerField(
                db_column="idetiqueta", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="etiqueta",
            old_name="idetiqueta",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="etiqueta",
            name="numerofaltante",
            field=models.IntegerField(db_column="numerofaltante"),
        ),
        migrations.RenameField(
            model_name="etiqueta",
            old_name="numerofaltante",
            new_name="termodesinfectora",
        ),
    ]
