# Generated by Django 4.1.12 on 2023-11-07 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0061_merge_20231107_1031"),
        ("common", "0063_rename_idproducao_evento_preparo"),
    ]

    operations = []
