# Generated by Django 4.1.13 on 2023-11-10 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0061_merge_20231107_0831"),
        (
            "common",
            "0063_distribuicao_created_at_distribuicao_created_by_and_more",
        ),
    ]

    operations = []
