# Generated by Django 4.1.12 on 2023-11-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0064_alter_diario_descricaoacaoocorrencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diario",
            name="id",
            field=models.BigAutoField(
                db_column="iddiario", primary_key=True, serialize=False
            ),
        ),
    ]
