# Generated by Django 4.1.13 on 2023-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0064_alter_etiqueta_numero_rename_numero_etiqueta_cautela_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="etiqueta",
            name="id",
            field=models.BigAutoField(
                db_column="idetiqueta", primary_key=True, serialize=False
            ),
        ),
    ]
