# Generated by Django 4.1.13 on 2023-11-08 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0061_merge_20231107_0831"),
        (
            "common",
            "0062_alter_autoclavagem_options_alter_cautela_options_and_more",
        ),
        ("common", "0065_alter_diario_id"),
    ]

    operations = []
