# Generated by Django 4.1.12 on 2023-11-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0065_alter_producao_options_alter_producao_ciclo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producao",
            name="id",
            field=models.BigAutoField(
                db_column="idproducao", primary_key=True, serialize=False
            ),
        ),
    ]
