# Generated by Django 4.1.13 on 2023-11-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0065_alter_etiqueta_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etiqueta",
            name="status",
            field=models.CharField(
                blank=True, default="VALIDO", max_length=10, null=True
            ),
        ),
    ]
