# Generated by Django 4.1.12 on 2023-11-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0066_alter_producao_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemproducao",
            name="iditemproducao",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
