# Generated by Django 4.1.13 on 2023-11-09 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0060_evento_created_at_evento_created_by_and_more"),
        ("common", "0066_alter_etiqueta_status"),
    ]

    operations = []
