# Generated by Django 4.1.12 on 2023-11-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0067_alter_itemproducao_iditemproducao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemproducao",
            name="statusproducaodistribuicaosequencial",
            field=models.BooleanField(default=False),
        ),
    ]
