# Generated by Django 4.1.13 on 2023-11-10 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0061_merge_20231107_0831"),
        (
            "common",
            "0062_alter_autoclavagem_options_alter_cautela_options_and_more",
        ),
        ("common", "0067_merge_20231109_1641"),
    ]

    operations = []
