# Generated by Django 4.1.12 on 2023-11-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0068_alter_itemproducao_statusproducaodistribuicaosequencial",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemproducao",
            name="iditemproducao",
            field=models.BigAutoField(
                db_column="iditemproducao", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="itemproducao",
            old_name="iditemproducao",
            new_name="id",
        ),
    ]
