# Generated by Django 4.1.13 on 2023-11-10 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0069_complemento_created_at_complemento_created_by_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="complemento",
            old_name="idcomplemento",
            new_name="id",
        ),
    ]
