# Generated by Django 4.1.12 on 2023-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0070_alter_producao_statusproducao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenciaetiqueta",
            name="data_ultima_situacao",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="sequenciaetiqueta",
            name="ultima_situacao",
            field=models.IntegerField(
                choices=[
                    (0, "Não Utilizado"),
                    (1, "Recebido"),
                    (2, "Manual"),
                    (3, "Termodesinfecção Inicio"),
                    (4, "Termodesinfecção Fim"),
                    (5, "Embalado"),
                    (6, "Esterilização Inicio"),
                    (7, "Esterilização Fim"),
                    (8, "Abortado"),
                    (9, "Distribuído"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
