# Generated by Django 4.1.13 on 2023-11-10 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0064_merge_20231109_2127"),
        ("common", "0070_rename_idcomplemento_complemento_id"),
    ]

    operations = []
