# Generated by Django 4.1.12 on 2023-11-08 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0064_merge_20231107_1208"),
        (
            "common",
            "0071_alter_sequenciaetiqueta_data_ultima_situacao_and_more",
        ),
    ]

    operations = []
