# Generated by Django 4.1.12 on 2023-11-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0071_alter_sequenciaetiqueta_data_ultima_situacao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemproducao",
            name="idproducao",
            field=models.ForeignKey(
                db_column="idproducao",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="itens",
                to="common.producao",
            ),
        ),
    ]
