# Generated by Django 4.1.13 on 2023-11-09 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0072_alter_itemproducao_idproducao"),
        ("common", "0072_merge_20231108_1421"),
    ]

    operations = []
