# Generated by Django 4.1.13 on 2023-11-10 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0071_merge_20231110_0009"),
        ("common", "0073_merge_20231109_1019"),
    ]

    operations = []
