# Generated by Django 4.1.13 on 2023-11-10 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0074_merge_20231110_1140"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producao",
            options={"managed": True, "verbose_name": "Produção"},
        ),
    ]
