# Generated by Django 4.1.13 on 2023-11-10 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0067_alter_diario_arquivo"),
        ("common", "0075_alter_producao_options"),
    ]

    operations = []
