# Generated by Django 4.1.13 on 2023-11-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0075_alter_producao_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoclavagem",
            name="idautoclavagem",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
