# Generated by Django 4.1.13 on 2023-11-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0076_alter_autoclavagem_idautoclavagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoclavagem",
            name="idautoclavagem",
            field=models.BigAutoField(
                db_column="idautoclavagem", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="autoclavagem",
            old_name="idautoclavagem",
            new_name="id",
        ),
    ]
