# Generated by Django 4.1.13 on 2023-11-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0078_autoclavagem_created_at_autoclavagem_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itensautoclavagem",
            name="iditensautoclavagem",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
