# Generated by Django 4.1.13 on 2023-11-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0079_alter_itensautoclavagem_iditensautoclavagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itensautoclavagem",
            name="iditensautoclavagem",
            field=models.BigAutoField(
                db_column="iditensautoclavagem",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RenameField(
            model_name="itensautoclavagem",
            old_name="iditensautoclavagem",
            new_name="id",
        ),
    ]
