# Generated by Django 4.1.13 on 2023-11-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0080_alter_itensautoclavagem_iditensautoclavagem_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="itensautoclavagem",
            old_name="idsequenciaetiqueta",
            new_name="serial",
        ),
        migrations.AlterField(
            model_name="itensautoclavagem",
            name="idautoclavagem",
            field=models.ForeignKey(
                db_column="idautoclavagem",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="itens",
                to="common.autoclavagem",
            ),
        ),
    ]
