# Generated by Django 4.1.13 on 2023-11-10 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0081_rename_idsequenciaetiqueta_itensautoclavagem_serial_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="itensautoclavagem",
            old_name="idautoclavagem",
            new_name="autoclavagem",
        ),
    ]
