# Generated by Django 4.1.13 on 2023-11-10 23:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "common",
            "0082_rename_idautoclavagem_itensautoclavagem_autoclavagem",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Itensautoclavagem",
            new_name="AutoclavagemItem",
        ),
    ]
