# Generated by Django 4.1.13 on 2023-11-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0083_rename_itensautoclavagem_autoclavagemitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenciaetiqueta",
            name="ultima_situacao",
            field=models.IntegerField(
                choices=[
                    (0, "Não Utilizado"),
                    (1, "Recebido"),
                    (2, "Manual"),
                    (3, "Em termodesinfecção"),
                    (4, "Termodesinfecção concluída"),
                    (5, "Embalado"),
                    (6, "Em esterilização"),
                    (7, "Esterilização concluída"),
                    (8, "Em estoque"),
                    (9, "Abortado"),
                    (10, "Distribuído"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
