# Generated by Django 4.1.13 on 2023-11-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0084_alter_sequenciaetiqueta_ultima_situacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoclavagem",
            name="tipolimpeza",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1", "P1"),
                    ("P2", "P2"),
                    ("P3", "P3"),
                    ("P4", "P4"),
                ],
                default=None,
                max_length=99,
                null=True,
            ),
        ),
    ]
