# Generated by Django 4.1.13 on 2023-11-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0085_alter_autoclavagem_tipolimpeza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoclavagem",
            name="tipolimpeza",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1", "P1"),
                    ("P2", "P2"),
                    ("P3", "P3"),
                    ("P4", "P4"),
                ],
                db_column="tipolimpeza",
                default=None,
                max_length=99,
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="autoclavagem",
            old_name="tipolimpeza",
            new_name="tipo_limpeza",
        ),
    ]
