# Generated by Django 4.1.13 on 2023-11-11 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0086_alter_autoclavagem_tipolimpeza_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autoclavagem",
            old_name="idequipamento",
            new_name="equipamento",
        ),
    ]
