# Generated by Django 4.1.13 on 2023-11-13 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0087_rename_idequipamento_autoclavagem_equipamento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autoclavagem",
            old_name="tipo_limpeza",
            new_name="programacao",
        ),
    ]
