# Generated by Django 4.1.13 on 2023-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0088_rename_tipo_limpeza_autoclavagem_programacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="proxima_manutencao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("TD", "Termodesinfectora"),
                    ("AC", "Autoclave"),
                    ("LU", "Lavadora Ultrassônica"),
                    ("SD", "Secadora"),
                    ("EG", "Esterilizador a Gás"),
                    ("BT", "Esterilizador de Baixa Temperatura"),
                    ("CB", "Cabine de Segurança Biológica"),
                    ("SL", "Seladora"),
                    ("DQ", "Desinfectora Química"),
                    ("CT", "Carrinho de Transporte"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="ultima_manutencao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autoclavagem",
            name="programacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1", "P1"),
                    ("P2", "P2"),
                    ("P3", "P3"),
                    ("P4", "P4"),
                    ("P5", "P5"),
                    ("P6", "P6"),
                    ("P7", "P7"),
                    ("P8", "P8"),
                    ("P9", "P9"),
                    ("P10", "P10"),
                    ("P11", "P11"),
                    ("P12", "P12"),
                ],
                db_column="tipolimpeza",
                default=None,
                max_length=99,
                null=True,
            ),
        ),
    ]
