# Generated by Django 4.1.13 on 2023-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0090_auto_20231113_1516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("TD", "Termodesinfectora"),
                    ("AC", "Autoclave"),
                    ("LU", "Lavadora Ultrassônica"),
                    ("SD", "Secadora"),
                    ("EG", "Esterilizador a Gás"),
                    ("BT", "Esterilizador de Baixa Temperatura"),
                    ("CB", "Cabine de Segurança Biológica"),
                    ("SL", "Seladora"),
                    ("DQ", "Desinfectora Química"),
                    ("CT", "Carrinho de Transporte"),
                ],
                default="AC",
                max_length=2,
            ),
        ),
    ]
