# Generated by Django 4.1.13 on 2023-11-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0091_alter_equipamento_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoque",
            name="idestoque",
            field=models.BigIntegerField(
                db_column="idestoque", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="estoque",
            old_name="idestoque",
            new_name="id",
        ),
    ]
