# Generated by Django 4.1.13 on 2023-11-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0092_alter_estoque_idestoque_rename_idestoque_estoque_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoque",
            name="id",
            field=models.BigAutoField(
                db_column="idestoque", primary_key=True, serialize=False
            ),
        ),
    ]
