# Generated by Django 4.1.13 on 2023-11-15 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0076_merge_20231110_1959"),
        ("common", "0094_rename_idsequenciaetiqueta_estoque_serial"),
    ]

    operations = []
