# Generated by Django 4.1.13 on 2023-11-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0095_merge_20231115_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoesterilizacaomodel",
            name="automatica",
            field=models.BooleanField(default=False),
        ),
    ]
