# Generated by Django 4.1.13 on 2023-11-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0096_solicitacaoesterilizacaomodel_automatica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrecebimento",
            name="idrecebimento",
            field=models.ForeignKey(
                db_column="idrecebimento",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="itens",
                to="common.recebimento",
            ),
        ),
    ]
