# Generated by Django 4.1.13 on 2023-11-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0097_alter_itemrecebimento_idrecebimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recebimento",
            name="idrecebimento",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
