# Generated by Django 4.1.13 on 2023-11-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0098_alter_recebimento_idrecebimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrecebimento",
            name="iditemrecebimento",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
