# Generated by Django 4.1.13 on 2023-11-23 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0099_alter_itemrecebimento_iditemrecebimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacaoesterilizacaomodel",
            name="automatica",
        ),
    ]
