# Generated by Django 4.1.13 on 2023-11-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0102_add_profissoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariogrupo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="grupos",
                to="common.usuario",
            ),
        ),
    ]
