# Generated by Django 4.1.13 on 2023-11-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="idgrupo",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
