# Generated by Django 4.1.13 on 2023-11-23 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0101_add_usuario_admin"),
        ("common", "0102_alter_usuariogrupo_usuario"),
    ]

    operations = []
