# Generated by Django 4.1.13 on 2023-11-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0103_merge_20231123_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenciaetiqueta",
            name="recebimento",
            field=models.ManyToManyField(
                related_name="seriais", to="common.recebimento"
            ),
        ),
    ]
