# Generated by Django 4.1.13 on 2023-11-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0104_alter_sequenciaetiqueta_recebimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="idproduto",
            field=models.BigIntegerField(
                db_column="idproduto", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="idproduto",
            new_name="id",
        ),
    ]
