# Generated by Django 4.1.13 on 2023-12-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0106_alter_produto_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="termodesinfeccao",
            old_name="idequipamento",
            new_name="equipamento",
        ),
        migrations.RenameField(
            model_name="termodesinfeccao",
            old_name="idtermodesinfeccao",
            new_name="id",
        ),
    ]
