# Generated by Django 4.1.13 on 2023-12-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0107_alter_indicador_idindicador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicador",
            name="idindicador",
            field=models.BigAutoField(
                db_column="idindicador", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="indicador",
            old_name="idindicador",
            new_name="id",
        ),
    ]
