# Generated by Django 4.1.13 on 2023-12-05 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0103_alter_grupo_idgrupo"),
        (
            "common",
            "0107_rename_idequipamento_termodesinfeccao_equipamento_and_more",
        ),
    ]

    operations = []
