# Generated by Django 4.1.13 on 2023-12-06 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0109_alter_itenstermodesinfeccao_idtermodesinfeccao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itenstermodesinfeccao",
            old_name="iditenstermodesinfeccao",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="itenstermodesinfeccao",
            old_name="idsequenciaetiqueta",
            new_name="serial",
        ),
        migrations.RenameField(
            model_name="itenstermodesinfeccao",
            old_name="idtermodesinfeccao",
            new_name="termodesinfeccao",
        ),
    ]
