# Generated by Django 4.1.13 on 2023-12-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0111_rename_iditenstermodesinfeccao_itenstermodesinfeccao_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="termodesinfeccao",
            name="tipolimpeza",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1", "P1"),
                    ("P2", "P2"),
                    ("P3", "P3"),
                    ("P4", "P4"),
                    ("P5", "P5"),
                    ("P6", "P6"),
                    ("P7", "P7"),
                    ("P8", "P8"),
                    ("P9", "P9"),
                    ("P10", "P10"),
                    ("P11", "P11"),
                    ("P12", "P12"),
                ],
                db_column="tipolimpeza",
                default=None,
                max_length=99,
                null=True,
            ),
        ),
    ]
