# Generated by Django 4.1.13 on 2023-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0112_alter_termodesinfeccao_tipolimpeza"),
    ]

    operations = [
        migrations.RenameField(
            model_name="termodesinfeccao",
            old_name="tipolimpeza",
            new_name="programacao",
        ),
    ]
