# Generated by Django 4.1.13 on 2023-12-15 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0109_rename_indicador_tipoocorrencia"),
        ("common", "0113_rename_tipolimpeza_termodesinfeccao_programacao"),
    ]

    operations = []
