# Generated by Django 4.1.13 on 2024-01-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0114_merge_20231215_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="bairrocli",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cepcli",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cidadecli",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cnpjcli",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CNPJ"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigocli",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="emailcli",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="inscricaoestadualcli",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                verbose_name="Inscrição Estadual",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nomeabreviado",
            field=models.CharField(
                max_length=90, unique=True, verbose_name="Sigla"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nomecli",
            field=models.CharField(
                max_length=90, unique=True, verbose_name="Razão Social"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nomefantasiacli",
            field=models.CharField(
                blank=True,
                max_length=90,
                null=True,
                verbose_name="Nome Fantasia",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numerocli",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Nº"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="ruacli",
            field=models.CharField(
                blank=True, max_length=90, null=True, verbose_name="Rua"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefonecli",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="ufcli",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="UF"
            ),
        ),
    ]
