# Generated by Django 4.1.13 on 2024-01-24 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0114_merge_20231215_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="nome",
            field=models.CharField(
                db_column="descricao",
                help_text="Nome descritivo, deve ser único.",
                max_length=90,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O nome só pode conter letras maiúsculas, números e espaços.",
                        regex="^[A-Z0-9 º°]+$",
                    )
                ],
            ),
        ),
    ]
