# Generated by Django 4.1.13 on 2024-01-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0114_merge_20231215_1336"),
    ]

    operations = [
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="processo/")),
                (
                    "nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "producao",
                    models.ForeignKey(
                        blank=True,
                        db_column="idproducao",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.producao",
                    ),
                ),
                (
                    "recebimento",
                    models.ForeignKey(
                        blank=True,
                        db_column="idrecebimento",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.recebimento",
                    ),
                ),
            ],
        ),
    ]
