# Generated by Django 4.1.13 on 2024-01-22 21:00

from django.db import migrations, models
import uuid


def preencher_uuids_unicos(apps, schema_editor):
    Equipamento = apps.get_model("common", "Equipamento")

    for equipamento in Equipamento.objects.filter(uuid__isnull=True):
        equipamento.uuid = uuid.uuid4()
        equipamento.save()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0114_merge_20231215_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="uuid",
            field=models.UUIDField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.RunPython(preencher_uuids_unicos),
    ]
