# Generated by Django 4.1.13 on 2024-02-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0115_add_gerente"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                db_column="cliente",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.cliente",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[("DIURNO", "Diurno"), ("NOTURNO", "Noturno")],
                max_length=10,
                null=True,
            ),
        ),
    ]
