# Generated by Django 4.1.13 on 2024-01-22 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0115_equipamento_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
    ]
