# Generated by Django 4.1.13 on 2024-02-07 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0115_alter_caixa_nome"),
        (
            "common",
            "0115_alter_cliente_bairrocli_alter_cliente_cepcli_and_more",
        ),
        ("common", "0115_midia"),
        ("common", "0116_alter_equipamento_uuid"),
    ]

    operations = []
