# Generated by Django 4.1.13 on 2024-02-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0116_evento_cliente_evento_turno"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoclavagem",
            name="duracao",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
