# Generated by Django 4.1.13 on 2024-02-08 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0117_merge_20240206_1419"),
        ("common", "0117_merge_20240207_1313"),
        ("common", "0117_merge_20240207_1359"),
    ]

    operations = []
