# Generated by Django 4.1.13 on 2024-02-29 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0117_autoclavagem_duracao"),
        ("common", "0118_merge_20240208_1614"),
    ]

    operations = []
