# Generated by Django 4.1.13 on 2024-02-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0118_merge_20240208_1614"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecebimentoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao",
                    models.IntegerField(
                        choices=[
                            (1, "Recebido"),
                            (11, "Aguardando_Conferencia"),
                        ],
                        default=11,
                        null=True,
                    ),
                ),
                (
                    "recebimento",
                    models.ForeignKey(
                        db_column="idrecebimento",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="recebimento",
                        to="common.recebimento",
                    ),
                ),
                (
                    "sequenciaetiqueta",
                    models.ForeignKey(
                        db_column="idsequenciaetiqueta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="seriais",
                        to="common.sequenciaetiqueta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do recebimento",
                "verbose_name_plural": "Itens do recebimento",
                "db_table": "recebimento_item",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="sequenciaetiqueta",
            name="recebimento_novo",
            field=models.ManyToManyField(
                related_name="sequenciais",
                through="common.RecebimentoItem",
                to="common.recebimento",
            ),
        ),
    ]
