# Generated by Django 4.1.13 on 2024-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0118_merge_20240208_1614"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenciaetiqueta",
            name="ultima_situacao",
            field=models.IntegerField(
                choices=[
                    (0, "Não Utilizado"),
                    (11, "Aguardando Conferência"),
                    (1, "Recebido"),
                    (2, "Manual"),
                    (3, "Em termodesinfecção"),
                    (4, "Termodesinfecção concluída"),
                    (5, "Embalado"),
                    (6, "Em esterilização"),
                    (7, "Esterilização concluída"),
                    (8, "Em estoque"),
                    (9, "Abortado em termodesinfecção"),
                    (10, "Distribuído"),
                    (12, "Abortado em esterilização"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
