# Generated by Django 4.1.13 on 2024-03-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0119_merge_20240229_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="termodesinfeccao",
            name="duracao",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
