# Generated by Django 4.1.13 on 2024-02-22 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0119_alter_sequenciaetiqueta_ultima_situacao"),
        ("common", "0120_auto_20240222_1156"),
    ]

    operations = []
