# Generated by Django 4.1.13 on 2024-02-22 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0124_alter_recebimentoitem_recebimento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sequenciaetiqueta",
            name="recebimento",
        ),
    ]
