# Generated by Django 4.1.13 on 2024-02-22 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0125_remove_sequenciaetiqueta_recebimento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sequenciaetiqueta",
            old_name="recebimento_novo",
            new_name="recebimento",
        ),
    ]
