# Generated by Django 4.1.13 on 2024-02-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0127_alter_sequenciaetiqueta_recebimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenciaetiqueta",
            name="recebimento",
            field=models.ManyToManyField(
                related_name="recebimentos",
                through="common.RecebimentoItem",
                to="common.recebimento",
            ),
        ),
    ]
