# Generated by Django 4.1.13 on 2024-02-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0128_alter_sequenciaetiqueta_recebimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recebimentoitem",
            name="serial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seriais_recebimento",
                to="common.sequenciaetiqueta",
            ),
        ),
    ]
