# Generated by Django 4.1.13 on 2024-02-23 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0119_equipamento_disponivel"),
        ("common", "0130_alter_recebimentoitem_recebimento_and_more"),
    ]

    operations = []
