# Generated by Django 4.1.13 on 2024-02-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0132_etiqueta_ciclo_autoclave_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etiqueta",
            name="ciclo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
