# Generated by Django 4.1.13 on 2024-02-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0133_alter_etiqueta_ciclo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etiqueta",
            name="termodesinfectora",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
