# Generated by Django 4.1.13 on 2024-02-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0134_alter_etiqueta_termodesinfectora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etiqueta",
            name="cautela",
            field=models.IntegerField(
                blank=True, db_column="numero", null=True
            ),
        ),
    ]
