# Generated by Django 4.1.13 on 2024-02-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0135_alter_etiqueta_cautela"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etiqueta",
            name="qtdimpressao",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
