# Generated by Django 4.1.13 on 2024-02-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0136_alter_etiqueta_qtdimpressao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etiqueta",
            name="seladora",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
