# Generated by Django 4.1.13 on 2024-04-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0137_alter_etiqueta_seladora"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribuicao",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.setor",
            ),
        ),
    ]
