# Generated by Django 4.1.13 on 2024-03-12 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0120_termodesinfeccao_duracao"),
        ("common", "0137_alter_etiqueta_seladora"),
    ]

    operations = []
