# Generated by Django 4.1.13 on 2024-03-13 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0137_alter_etiqueta_seladora"),
    ]

    operations = [
        migrations.AddField(
            model_name="etiqueta",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                db_column="setor",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.setor",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEtiqueta",
            fields=[
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        null=True,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        null=True,
                        verbose_name="updated_at",
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        blank=True, db_column="idetiqueta", db_index=True
                    ),
                ),
                ("autoclave", models.IntegerField(blank=True, null=True)),
                (
                    "biologico",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("ciclo", models.IntegerField(blank=True, null=True)),
                (
                    "ciclo_autoclave",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ciclo_termodesinfectora",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("datafabricacao", models.DateField()),
                ("datalancamento", models.DateField()),
                ("datavalidade", models.DateField()),
                ("horalancamento", models.TimeField()),
                (
                    "cautela",
                    models.IntegerField(
                        blank=True, db_column="numero", null=True
                    ),
                ),
                (
                    "termodesinfectora",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "obs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "peso",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("qtd", models.IntegerField()),
                ("qtdimpressao", models.IntegerField(blank=True, null=True)),
                (
                    "seladora",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("servico", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="VALIDO", max_length=10, null=True
                    ),
                ),
                ("temperatura", models.IntegerField(blank=True, null=True)),
                ("tipoetiqueta", models.CharField(max_length=20)),
                (
                    "totalenvelopado",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idcli",
                    models.ForeignKey(
                        blank=True,
                        db_column="idcli",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="common.cliente",
                    ),
                ),
                (
                    "idcomplemento",
                    models.ForeignKey(
                        blank=True,
                        db_column="idcomplemento",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="common.complemento",
                    ),
                ),
                (
                    "idproduto",
                    models.ForeignKey(
                        blank=True,
                        db_column="idproduto",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="common.produto",
                    ),
                ),
                (
                    "idprofissional",
                    models.ForeignKey(
                        blank=True,
                        db_column="idprofissional",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="common.profissional",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        blank=True,
                        db_column="setor",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="common.setor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Etiqueta",
                "verbose_name_plural": "historical Etiquetas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
