# Generated by Django 4.1.13 on 2024-04-02 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0137_alter_etiqueta_seladora"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        null=True,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        null=True,
                        verbose_name="updated_at",
                    ),
                ),
                ("codigo", models.CharField(unique=True, max_length=15)),
                ("saldo", models.IntegerField(default=0)),
                ("fabricacao", models.DateField()),
                ("vencimento", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "db_table": "lote",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IndicadoresEsterilizacao",
            fields=[],
            options={
                "verbose_name": "Indicador",
                "verbose_name_plural": "Indicadores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.produto",),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo",
            field=models.CharField(
                unique=True, blank=True, max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="fabricante",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="saldo",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Classe 02", "Teste de Bowie & Dick"),
                    ("Classe 05", "Integrador Químico"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="idsubtipoproduto",
            field=models.ForeignKey(
                blank=True,
                db_column="idsubtipoproduto",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.subtipoproduto",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="idtipopacote",
            field=models.ForeignKey(
                blank=True,
                db_column="idtipopacote",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.tipopacote",
            ),
        ),
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        null=True,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        null=True,
                        verbose_name="updated_at",
                    ),
                ),
                (
                    "operacao",
                    models.CharField(
                        choices=[("ENTRADA", "ENTRADA"), ("SAIDA", "SAIDA")],
                        max_length=10,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        db_column="lote_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.lote",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação do estoque",
                "verbose_name_plural": "Movimentações do estoque",
                "db_table": "movimentacao_estoque",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="lote",
            name="indicador",
            field=models.ForeignKey(
                db_column="indicador_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.indicadoresesterilizacao",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lote",
            unique_together={("codigo", "indicador")},
        ),
    ]
