# Generated by Django 4.1.13 on 2024-03-13 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0138_etiqueta_setor_historicaletiqueta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etiqueta",
            old_name="autoclave",
            new_name="autoclave_legado",
        ),
        migrations.RenameField(
            model_name="etiqueta",
            old_name="seladora",
            new_name="seladora_legado",
        ),
        migrations.RenameField(
            model_name="etiqueta",
            old_name="termodesinfectora",
            new_name="termodesinfectora_legado",
        ),
        migrations.RenameField(
            model_name="historicaletiqueta",
            old_name="autoclave",
            new_name="autoclave_legado",
        ),
        migrations.RenameField(
            model_name="historicaletiqueta",
            old_name="seladora",
            new_name="seladora_legado",
        ),
        migrations.RenameField(
            model_name="historicaletiqueta",
            old_name="termodesinfectora",
            new_name="termodesinfectora_legado",
        ),
    ]
