# Generated by Django 4.1.13 on 2024-04-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0138_lote_indicadoresesterilizacao_produto_codigo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="producao",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.indicadoresesterilizacao",
            ),
        ),
    ]
