# Generated by Django 4.1.13 on 2024-03-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0139_rename_autoclave_etiqueta_autoclave_legado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etiqueta",
            name="autoclave",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="autoclave_etiquetas",
                to="common.equipamento",
            ),
        ),
        migrations.AddField(
            model_name="etiqueta",
            name="seladora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seladora_etiquetas",
                to="common.equipamento",
            ),
        ),
        migrations.AddField(
            model_name="etiqueta",
            name="termodesinfectora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="termodesinfectora_etiquetas",
                to="common.equipamento",
            ),
        ),
        migrations.AddField(
            model_name="historicaletiqueta",
            name="autoclave",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.equipamento",
            ),
        ),
        migrations.AddField(
            model_name="historicaletiqueta",
            name="seladora",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.equipamento",
            ),
        ),
        migrations.AddField(
            model_name="historicaletiqueta",
            name="termodesinfectora",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.equipamento",
            ),
        ),
    ]
