# Generated by Django 4.1.13 on 2024-03-18 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0140_registromanutencao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registromanutencao",
            name="duracao_em_segundos",
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="fim_planejado",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="inicio_planejado",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="equipamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="equipamentos_manutencao",
                to="common.equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="inicio",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="usuarios_manutencao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
