# Generated by Django 4.1.13 on 2024-03-27 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0140_etiqueta_autoclave_etiqueta_seladora_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etiqueta",
            name="autoclave_legado",
        ),
        migrations.RemoveField(
            model_name="etiqueta",
            name="seladora_legado",
        ),
        migrations.RemoveField(
            model_name="etiqueta",
            name="termodesinfectora_legado",
        ),
        migrations.RemoveField(
            model_name="historicaletiqueta",
            name="autoclave_legado",
        ),
        migrations.RemoveField(
            model_name="historicaletiqueta",
            name="seladora_legado",
        ),
        migrations.RemoveField(
            model_name="historicaletiqueta",
            name="termodesinfectora_legado",
        ),
    ]
