# Generated by Django 4.1.13 on 2024-04-12 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0138_add_fk_setor_on_distribuicao"),
        ("common", "0141_remove_etiqueta_autoclave_legado_and_more"),
    ]

    operations = []
