# Generated by Django 4.1.13 on 2024-03-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0141_remove_registromanutencao_duracao_em_segundos_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="registromanutencao",
            name="inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
