# Generated by Django 4.1.13 on 2024-03-21 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0142_alter_registromanutencao_inicio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registromanutencao",
            old_name="observacao",
            new_name="descricao",
        ),
    ]
