# Generated by Django 4.1.13 on 2024-04-15 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0142_merge_20240412_1850"),
        ("common", "0145_auto_20240328_1618"),
    ]

    operations = []
