# Generated by Django 4.1.13 on 2024-04-15 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0138_lote_indicadoresesterilizacao_produto_codigo_and_more",
        ),
        ("common", "0146_merge_20240415_1516"),
    ]

    operations = []
