# Generated by Django 4.1.13 on 2024-04-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0146_merge_20240415_1516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complemento",
            name="descricao",
            field=models.CharField(
                error_messages={
                    "unique": "Já existe um %(model_name)s com esta %(field_label)s."
                },
                max_length=255,
                unique=True,
                verbose_name="descrição",
            ),
        ),
    ]
