# Generated by Django 4.1.13 on 2024-04-17 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0139_producao_indicador"),
        ("common", "0147_merge_20240415_1738"),
    ]

    operations = []
