# Generated by Django 4.1.13 on 2024-04-22 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0147_alter_complemento_descricao"),
        ("common", "0149_autoclavagem_indicador_and_more"),
    ]

    operations = []
