# Generated by Django 4.1.13 on 2024-05-23 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0148_auto_20240507_1534"),
        ("common", "0150_merge_20240422_1759"),
    ]

    operations = []
