# Generated by Django 4.1.9 on 2023-06-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="admin", max_length=60, unique=True
            ),
        ),
    ]
