# Generated by Django 4.1.9 on 2023-06-21 08:10

from django.db import migrations
from common import models
from users.models import User
from django.utils import timezone


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        for person in models.Usuario.objects.all():
            User.objects.create_usermigrations(
                id=person.idusu,
                created=timezone.make_aware(person.datacadastrousu),
                username=person.apelidousu,
                password="bcrypt$" + person.senhausu,
                idprofissional=person.idprofissional,
                email="",
                is_active=person.ativo,
            )
        query = "SELECT setval(pg_get_serial_sequence('{0}', 'id'), coalesce((SELECT MAX(id)+1 FROM {0}), 1), false);".format(
            User._meta.db_table
        )
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(query)

    def backwards_func(apps, schema_editor):
        User = apps.get_model("users", "User")
        Usuario = apps.get_model("common", "Usuario")
        user_ids = Usuario.objects.values_list("idusu", flat=True)
        User.objects.filter(id__in=user_ids).delete()

    dependencies = [
        ("users", "0003_alter_user_email_alter_user_username"),
        ("common", "0011_profissional_cliente"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
