# Generated by Django 4.1.10 on 2023-07-11 14:19
from django.db import migrations
from common import models
from django.contrib.auth.models import Group
from users.models import User


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        for group in models.Grupo.objects.all():
            grupos = Group.objects.create(id=group.idgrupo, name=group.nome)

        query = "SELECT setval(pg_get_serial_sequence('{0}', 'id'), coalesce((SELECT MAX(id)+1 FROM {0}), 1), false);".format(
            Group._meta.db_table
        )
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(query)

        Group.objects.create(name="MOTORISTA")
        Group.objects.create(name="CLIENTE")

        for usuario_grupo in models.UsuarioGrupo.objects.all():
            user = usuario_grupo.usuario_id
            group = usuario_grupo.grupo_id
            userfinal = User.objects.get(id=user)
            userfinal.groups.add(group)

    def backwards_func(apps, schema_editor):
        for group in models.Grupo.objects.all():
            grupo = Group.objects.get(id=group.idgrupo, name=group.nome)
            grupo.delete()

        motorista = Group.objects.get(name="MOTORISTA")
        motorista.delete()
        cliente = Group.objects.get(name="CLIENTE")
        cliente.delete()

    dependencies = [
        ("users", "0004_auto_20230621_2243"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
