# Generated by Django 4.1.12 on 2023-10-20 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_auto_20230711_1119"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[],
            options={
                "verbose_name": "Motorista",
                "verbose_name_plural": "Motoristas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
    ]
