# Generated by Django 4.1.12 on 2023-10-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0058_coletaentregamodel_situacao_and_more"),
        ("users", "0006_motorista"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="idprofissional",
            field=models.ForeignKey(
                blank=True,
                db_column="idprofissional",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="usuario",
                to="common.profissional",
            ),
        ),
    ]
